### ISSUE TITLE
Qt5 WebEngine application segfaults 

### ISSUE THREAD

**Issue by Paullux** [AppImageCrafters/appimage-builder#129]
i would like create an appimage from

https://github.com/handyopensource/dvkbuntu-easy-menu-qt/tree/Am%C3%A9lioration_et_vers_Appimage (this branch)

i can pass test, but when i would like launch the appimage i have its error : Trappe pour point d'arrêt et de trace (core dumped)

my recipe is : AppImageBuilder.yml
```yml
# appimage-builder recipe see https://appimage-builder.readthedocs.io for details
version: 1
script: |
    # remove any existent binaries
    rm -rf AppDir | true

    # compile and install binaries into AppDir
    cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
    make install DESTDIR=AppDir
AppDir:
  path: ./AppDir
  app_info:
    id: dvkbuntu-easy-menu
    name: Easy menu
    icon: dvkbuntu-easy-menu
    version: '4.16'
    exec: usr/bin/dvkbuntu-easy-menu
    exec_args: $@
  apt:
    arch: amd64
    allow_unauthenticated: true
    sources:
    - sourceline: deb http://fr.archive.ubuntu.com/ubuntu/ hirsute main restricted
    - sourceline: deb http://fr.archive.ubuntu.com/ubuntu/ hirsute-updates main restricted
    - sourceline: deb http://fr.archive.ubuntu.com/ubuntu/ hirsute universe
    - sourceline: deb http://fr.archive.ubuntu.com/ubuntu/ hirsute-updates universe
    - sourceline: deb http://fr.archive.ubuntu.com/ubuntu/ hirsute multiverse
    - sourceline: deb http://fr.archive.ubuntu.com/ubuntu/ hirsute-updates multiverse
    - sourceline: deb http://fr.archive.ubuntu.com/ubuntu/ hirsute-backports main
        restricted universe multiverse
    - sourceline: deb http://security.ubuntu.com/ubuntu hirsute-security main restricted
    - sourceline: deb http://security.ubuntu.com/ubuntu hirsute-security universe
    - sourceline: deb http://security.ubuntu.com/ubuntu hirsute-security multiverse
    include:
    - fonts-lohit-beng-bengali
    - fonts-tlwg-loma
    - kimageformat-plugins
    - fonts-khmeros-core
    - libpcre2-8-0
    - fonts-noto-cjk
    - tzdata
    - qt5-gtk-platformtheme
    - libpci3
    - fonts-guru-extra
    - libxshmfence1
    - fonts-telu-extra
    - fonts-noto-core
    - fonts-opensymbol
    - fonts-tlwg-waree
    - fonts-lohit-guru
    - libxrender1
    - fonts-smc-uroob
    - libxdmcp6
    - libxxf86vm1
    - gstreamer1.0-x
    - qttranslations5-l10n
    - fonts-smc-raghumalayalamsans
    - fonts-smc-dyuthi
    - kde-style-breeze
    - fonts-lohit-knda
    - libxfixes3
    - fonts-smc-keraleeyam
    - fonts-lohit-gujr
    - fonts-smc-anjalioldlipi
    - gstreamer1.0-plugins-bad
    - plasma-integration
    - fonts-smc-manjari
    - liblz4-1
    - gstreamer1.0-plugins-base
    - fonts-noto-mono
    - qtwayland5
    - fonts-smc-suruma
    - breeze-icon-theme
    - fonts-lohit-mlym
    - qt5-image-formats-plugins
    - libfam0
    - fonts-lohit-deva
    - fonts-smc-chilanka
    - fonts-tlwg-umpush
    - fonts-pagul
    - fonts-smc-karumbi
    - libxv1
    - libqt5webenginewidgets5
    - libxext6
    - libsm6
    - fonts-tlwg-garuda
    - fonts-gubbi
    - libxcb-xinerama0
    - libc-bin
    - qtspeech5-flite-plugin
    - libdebuginfod1
    - plasma-workspace-data
    - fonts-tlwg-laksaman
    - libjpeg-turbo8
    - fonts-gujr-extra
    - kde-style-oxygen-qt5
    - fonts-tlwg-typo
    - qtspeech5-speechd-plugin
    - fonts-orya-extra
    - libxrandr2
    - fonts-deva-extra
    - libxcb-xkb1
    - fonts-lohit-orya
    - fonts-smc-rachana
    - fonts-urw-base35
    - libqt5multimedia5-plugins
    - libsystemd0
    - libxcb-sync1
    - libxcb-render-util0
    - fonts-smc-meera
    - fonts-tlwg-typist
    - libkf5iconthemes-bin
    - kubuntu-settings-desktop
    - fonts-lohit-telu
    - libxtst6
    - fonts-lohit-taml
    - fonts-tlwg-kinnari
    - fonts-droid-fallback
    - qtvirtualkeyboard-plugin
    - fonts-tlwg-mono
    - fonts-tlwg-norasi
    - fonts-beng-extra
    - fonts-lohit-taml-classical
    - breeze-cursor-theme
    - language-selector-common
    - libunwind8
    - fonts-hack
    - fonts-lohit-beng-assamese
    - hwdata
    - gstreamer1.0-plugins-good
    - language-pack-fr-base
    exclude: []
  files:
    include: []
    exclude:
    - usr/share/man
    - usr/share/doc/*/README.*
    - usr/share/doc/*/changelog.*
    - usr/share/doc/*/NEWS.*
    - usr/share/doc/*/TODO.*
  test:
    fedora:
      image: appimagecrafters/tests-env:fedora-30
      command: ./AppRun
      use_host_x: true
    debian:
      image: appimagecrafters/tests-env:debian-stable
      command: ./AppRun
      use_host_x: true
    arch:
      image: appimagecrafters/tests-env:archlinux-latest
      command: ./AppRun
      use_host_x: true
    centos:
      image: appimagecrafters/tests-env:centos-7
      command: ./AppRun
      use_host_x: true
    ubuntu:
      image: appimagecrafters/tests-env:ubuntu-xenial
      command: ./AppRun
      use_host_x: true
AppImage:
  arch: x86_64
  update-information: guess
  sign-key: None
```
If i launch my appimage with --no-sandbox option, that work correctly ! Why ????
I am on kubuntu.

**Comment by azubieta** [comment]
This is a known Qt5 WebEngine issue, you need to disable sanboxing for the whole bundle. Use the snippet below to do it.

```
 runtime:
    env:
      # Disable webengine sandboxing
      QTWEBENGINE_DISABLE_SANDBOX: 1
```
