### ISSUE TITLE
AppImage fails to load on other computers (interpreter is hardcoded when reusing the AppDir accross invocations)

### ISSUE THREAD

**Issue by alex-tee** [AppImageCrafters/appimage-builder#135]
I built an appimage for zrythm (<https://git.zrythm.org/zrythm/zrythm>) and it worked locally, then I moved it to another pc and it said "APPRUN_ERROR: No such file or directory" when I ran it. I extracted it on the other pc and did `file squashfs-root/usr/bin/zrythm`, which said `squashfs-root/usr/bin/zrythm: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /tmp/appimage-d390d653-0f2b-44db-851c-241492b3aa55-ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=001204e3bc1fe973b462663b0a935b1fa4cb937c, with debug_info, not stripped`. I can't even run that  file directly, it says "no such file or directory" even though it's there. It looks like it's looking for  `/tmp/appimage-d390d653-0f2b-44db-851c-241492b3aa55-ld-linux-x86-64.so` for some reason.

here is the produced AppImage: http://www.zrythm.org/downloads/zrythm-4.4.20-x86_64.AppImage

Steps I took to build the AppImage:
1. prepare the following `appimage-builder.yaml` 

```yaml
version: 1

AppDir:
  path: /tmp/AppDir

  app_info:
    id: org.zrythm.Zrythm
    name: zrythm
    icon: utilities-terminal
    version: 4.4.20
    exec: usr/bin/zrythm
    exec_args: --appimage-runtime-path=$APPDIR $@

  apt:
    arch: amd64
    sources:
      - sourceline: 'deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ bionic main'
        key_url: 'http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3b4fe6acc0b21f32'
      - sourceline: 'deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ bionic universe'
        key_url: 'http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3b4fe6acc0b21f32'
      - sourceline: 'deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ bionic-updates main'
        key_url: 'http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3b4fe6acc0b21f32'
      - sourceline: 'deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ bionic-updates universe'
        key_url: 'http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3b4fe6acc0b21f32'

    include:
      - libglib2.0-0
      - libgtk-3-0
      - coreutils
      - bash
      - librsvg2-common
      - gettext
      - libcurl3-gnutls
      - libjack-jackd2-0
      - libsndfile1
      - libasound2
      - libgtksourceview-3.0-common
      - graphviz
      - librubberband2
      - libx11-6
      - libfftw3-3
      - libsamplerate0
      - libyaml-0-2
      - libxxhash0
      - breeze-icon-theme
    exclude:
      - dpkg

  test:
    fedora:
      image: fedora:32
      command: "./AppRun --version"
      use_host_x: True


AppImage:
  update-information: None
  sign-key: None
  arch: x86_64
```

2. compiled the program using `meson build -Dprefix=/usr` and then `DESTDIR=/tmp/AppDir ninja -C build install` to create the AppDir
3. run `appimage-builder --recipe ./appimage-builder.yml --skip-test`

# additional info
I was reusing the same AppDir over and over. the issue got resolved after removing it and using a freshly created one
