### ISSUE TITLE
error: no targets specified (use -h for help)

### ISSUE THREAD

**Issue by colatea** [AppImageCrafters/appimage-builder#136]
```
appimage-builder --recipe AppImageBuilder.yml
。。。。。
gpg: next trustdb check due at 2021-07-19
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
error: no targets specified (use -h for help)
ERROR:root:"['/usr/bin/pacman', '--config', '/tmp/appimage-builder-cache/pacman/pacman.conf', '-S', '--print-format', '%n=%v', '--noconfirm']" execution failed
Traceback (most recent call last):
  File "/usr/bin/appimage-builder", line 8, in <module>
    sys.exit(__main__())
  File "/usr/lib/python3.9/site-packages/appimagebuilder/__main__.py", line 57, in __main__
    invoker.execute(commands)
  File "/usr/lib/python3.9/site-packages/appimagebuilder/invoker.py", line 41, in execute
    command()
  File "/usr/lib/python3.9/site-packages/appimagebuilder/commands/pacman_deploy.py", line 50, in __call__
    deployed_packages = pacman_deploy.deploy(
  File "/usr/lib/python3.9/site-packages/appimagebuilder/modules/deploy/pacman/deploy.py", line 70, in deploy
    package_files = self.pacman_venv.retrieve(packages, exclude)
  File "/usr/lib/python3.9/site-packages/appimagebuilder/modules/deploy/pacman/venv.py", line 71, in retrieve
    initial_install_list = self._run_pacman_list_packages_and_versions(
  File "/usr/lib/python3.9/site-packages/appimagebuilder/modules/deploy/pacman/venv.py", line 116, in _run_pacman_list_packages_and_versions
    output = self._run_command(
  File "/usr/lib/python3.9/site-packages/appimagebuilder/modules/deploy/pacman/venv.py", line 234, in _run_command
    shell.assert_successful_result(_proc)
  File "/usr/lib/python3.9/site-packages/appimagebuilder/utils/shell.py", line 36, in assert_successful_result
    raise RuntimeError(
RuntimeError: "['/usr/bin/pacman', '--config', '/tmp/appimage-builder-cache/pacman/pacman.conf', '-S', '--print-format', '%n=%v', '--noconfirm']" execution failed with code 1
```
cat AppImageBuilder.yml 
```
# appimage-builder recipe see https://appimage-builder.readthedocs.io for details
version: 1
AppDir:
  path: /tmp/AppDir
  app_info:
    id: com.colatea.rename
    name: Colatea Renam
    icon: application-vnd.appimage
    version: 0.1.0
    exec: colatea_rename
    exec_args: $@
  pacman:
    include: []
    exclude: []
  files:
    include:
    - /home/colatea/.local/share/mime//mime.cache
    - /lib64/ld-linux-x86-64.so.2
    - /usr/lib/../lib/libedit.so.0
    - /usr/lib/../lib/libncursesw.so.6
    - /usr/lib/dri/iris_dri.so
    - /usr/lib/gconv/gconv-modules
    - /usr/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so
    - /usr/lib/gio/modules/libdconfsettings.so
    - /usr/lib/gio/modules/libgsettingsgconfbackend.so
    - /usr/lib/gio/modules/libgvfsdbus.so
    - /usr/lib/gtk-3.0/3.0.0/immodules.cache
    - /usr/lib/gtk-3.0/3.0.0/immodules/im-fcitx.so
    - /usr/lib/gvfs/libgvfscommon.so
    - /usr/lib/ld-linux-x86-64.so.2
    - /usr/lib/libEGL_mesa.so.0
    - /usr/lib/libGLX.so.0
    - /usr/lib/libGLdispatch.so.0
    - /usr/lib/libLLVM-12.so
    - /usr/lib/libOpenGL.so.0
    - /usr/lib/libX11.so.6
    - /usr/lib/libXau.so.6
    - /usr/lib/libXcomposite.so.1
    - /usr/lib/libXcursor.so.1
    - /usr/lib/libXdamage.so.1
    - /usr/lib/libXdmcp.so.6
    - /usr/lib/libXext.so.6
    - /usr/lib/libXfixes.so.3
    - /usr/lib/libXi.so.6
    - /usr/lib/libXinerama.so.1
    - /usr/lib/libXrandr.so.2
    - /usr/lib/libXrender.so.1
    - /usr/lib/libXxf86vm.so.1
    - /usr/lib/libatk-1.0.so.0
    - /usr/lib/libatk-bridge-2.0.so.0
    - /usr/lib/libatspi.so.0
    - /usr/lib/libblkid.so.1
    - /usr/lib/libbz2.so.1.0
    - /usr/lib/libc.so.6
    - /usr/lib/libcairo-gobject.so.2
    - /usr/lib/libcairo.so.2
    - /usr/lib/libcap.so.2
    - /usr/lib/libcloudproviders.so.0
    - /usr/lib/libdatrie.so.1
    - /usr/lib/libdbus-1.so.3
    - /usr/lib/libdbus-glib-1.so.2
    - /usr/lib/libdl.so.2
    - /usr/lib/libelf.so.1
    - /usr/lib/libepoxy.so.0
    - /usr/lib/libexpat.so.1
    - /usr/lib/libfcitx-gclient.so.1
    - /usr/lib/libfcitx-utils.so.0
    - /usr/lib/libffi.so.7
    - /usr/lib/libfontconfig.so.1
    - /usr/lib/libfreetype.so.6
    - /usr/lib/libfribidi.so.0
    - /usr/lib/libgbm.so.1
    - /usr/lib/libgcc_s.so.1
    - /usr/lib/libgconf-2.so.4
    - /usr/lib/libgcrypt.so.20
    - /usr/lib/libgdk-3.so.0
    - /usr/lib/libgdk_pixbuf-2.0.so.0
    - /usr/lib/libgio-2.0.so.0
    - /usr/lib/libglapi.so.0
    - /usr/lib/libglib-2.0.so.0
    - /usr/lib/libgmodule-2.0.so.0
    - /usr/lib/libgobject-2.0.so.0
    - /usr/lib/libgpg-error.so.0
    - /usr/lib/libgraphite2.so.3
    - /usr/lib/libgtk-3.so.0
    - /usr/lib/libharfbuzz.so.0
    - /usr/lib/libicudata.so.69
    - /usr/lib/libicuuc.so.69
    - /usr/lib/libjpeg.so.8
    - /usr/lib/liblz4.so.1
    - /usr/lib/liblzma.so.5
    - /usr/lib/libm.so.6
    - /usr/lib/libmount.so.1
    - /usr/lib/libnss_files.so.2
    - /usr/lib/libpango-1.0.so.0
    - /usr/lib/libpangocairo-1.0.so.0
    - /usr/lib/libpangoft2-1.0.so.0
    - /usr/lib/libpcre.so.1
    - /usr/lib/libpixman-1.so.0
    - /usr/lib/libpng16.so.16
    - /usr/lib/libpthread.so.0
    - /usr/lib/libresolv.so.2
    - /usr/lib/librsvg-2.so.2
    - /usr/lib/librt.so.1
    - /usr/lib/libsensors.so.5
    - /usr/lib/libstdc++.so.6
    - /usr/lib/libsystemd.so.0
    - /usr/lib/libthai.so.0
    - /usr/lib/libtiff.so.5
    - /usr/lib/libvulkan.so.1
    - /usr/lib/libwayland-client.so.0
    - /usr/lib/libwayland-cursor.so.0
    - /usr/lib/libwayland-egl.so.1
    - /usr/lib/libwayland-server.so.0
    - /usr/lib/libxcb-dri2.so.0
    - /usr/lib/libxcb-dri3.so.0
    - /usr/lib/libxcb-present.so.0
    - /usr/lib/libxcb-sync.so.1
    - /usr/lib/libxkbcommon.so.0
    - /usr/lib/libxml2.so.2
    - /usr/lib/libxshmfence.so.1
    - /usr/lib/libz.so.1
    - /usr/lib/libzstd.so.1
    - /usr/lib/locale/locale-archive
    - /usr/share//mime//mime.cache
    - /usr/share/X11/locale/compose.dir
    - /usr/share/X11/locale/en_US.UTF-8/Compose
    - /usr/share/X11/locale/en_US.UTF-8/XLC_LOCALE
    - /usr/share/X11/locale/locale.alias
    - /usr/share/X11/locale/locale.dir
    - /usr/share/drirc.d/00-mesa-defaults.conf
    - /usr/share/fonts/TTF/DejaVuSans-Bold.ttf
    - /usr/share/fonts/TTF/DejaVuSans-BoldOblique.ttf
    - /usr/share/fonts/TTF/DejaVuSans-ExtraLight.ttf
    - /usr/share/fonts/TTF/DejaVuSans-Oblique.ttf
    - /usr/share/fonts/TTF/DejaVuSans.ttf
    - /usr/share/fonts/TTF/DejaVuSansCondensed-Bold.ttf
    - /usr/share/fonts/TTF/DejaVuSansCondensed-BoldOblique.ttf
    - /usr/share/fonts/TTF/DejaVuSansCondensed-Oblique.ttf
    - /usr/share/fonts/TTF/DejaVuSansCondensed.ttf
    - /usr/share/fonts/liberation/LiberationSans-Bold.ttf
    - /usr/share/fonts/liberation/LiberationSans-BoldItalic.ttf
    - /usr/share/fonts/liberation/LiberationSans-Italic.ttf
    - /usr/share/fonts/liberation/LiberationSans-Regular.ttf
    - /usr/share/fonts/winfonts/ARIALN.TTF
    - /usr/share/fonts/winfonts/ARIALNB.TTF
    - /usr/share/fonts/winfonts/ARIALNBI.TTF
    - /usr/share/fonts/winfonts/ARIALNI.TTF
    - /usr/share/fonts/winfonts/arial.ttf
    - /usr/share/fonts/winfonts/arialbd.ttf
    - /usr/share/fonts/winfonts/arialbi.ttf
    - /usr/share/fonts/winfonts/ariali.ttf
    - /usr/share/fonts/winfonts/ariblk.ttf
    - /usr/share/fonts/winfonts/msyh.ttc
    - /usr/share/glvnd/egl_vendor.d/50_mesa.json
    - /usr/share/gtk-3.0/settings.ini
    - /usr/share/icons/Adwaita/icon-theme.cache
    - /usr/share/icons/Adwaita/index.theme
    - /usr/share/icons/Papirus-Dark-Maia/icon-theme.cache
    - /usr/share/icons/Papirus-Dark-Maia/index.theme
    - /usr/share/icons/Papirus-Dark/icon-theme.cache
    - /usr/share/icons/Papirus-Dark/index.theme
    - /usr/share/icons/Papirus-Dark/symbolic/actions/window-close-symbolic.svg
    - /usr/share/icons/Papirus-Dark/symbolic/actions/window-maximize-symbolic.svg
    - /usr/share/icons/Papirus-Dark/symbolic/actions/window-minimize-symbolic.svg
    - /usr/share/icons/Papirus/icon-theme.cache
    - /usr/share/icons/Papirus/index.theme
    - /usr/share/icons/default/index.theme
    - /usr/share/icons/hicolor/icon-theme.cache
    - /usr/share/icons/hicolor/index.theme
    - /usr/share/icons/xcursor-breeze/cursors/bottom_left_corner
    - /usr/share/icons/xcursor-breeze/cursors/bottom_right_corner
    - /usr/share/icons/xcursor-breeze/cursors/default
    - /usr/share/icons/xcursor-breeze/cursors/e-resize
    - /usr/share/icons/xcursor-breeze/cursors/n-resize
    - /usr/share/icons/xcursor-breeze/cursors/s-resize
    - /usr/share/icons/xcursor-breeze/cursors/text
    - /usr/share/icons/xcursor-breeze/cursors/top_left_corner
    - /usr/share/icons/xcursor-breeze/cursors/top_right_corner
    - /usr/share/icons/xcursor-breeze/cursors/w-resize
    - /usr/share/icons/xcursor-breeze/index.theme
    - /usr/share/locale/en/LC_MESSAGES/gtk30-properties.mo
    - /usr/share/locale/en/LC_MESSAGES/gtk30.mo
    - /usr/share/locale/locale.alias
    - /usr/share/themes/Default/gtk-3.0/gtk-keys.css
    - /usr/share/themes/Matcha-sea/gtk-3.0/assets/titlebutton-close-active-dark.png
    - /usr/share/themes/Matcha-sea/gtk-3.0/assets/titlebutton-close-backdrop-dark.png
    - /usr/share/themes/Matcha-sea/gtk-3.0/assets/titlebutton-close-dark.png
    - /usr/share/themes/Matcha-sea/gtk-3.0/assets/titlebutton-close-hover-dark.png
    - /usr/share/themes/Matcha-sea/gtk-3.0/assets/titlebutton-maximize-backdrop-dark.png
    - /usr/share/themes/Matcha-sea/gtk-3.0/assets/titlebutton-maximize-dark.png
    - /usr/share/themes/Matcha-sea/gtk-3.0/assets/titlebutton-minimize-backdrop-dark.png
    - /usr/share/themes/Matcha-sea/gtk-3.0/assets/titlebutton-minimize-dark.png
    - /usr/share/themes/Matcha-sea/gtk-3.0/assets/titlebutton-minimize-hover-dark.png
    - /usr/share/themes/Matcha-sea/gtk-3.0/gtk.css
    exclude:
    - usr/share/man
    - usr/share/doc/*/README.*
    - usr/share/doc/*/changelog.*
    - usr/share/doc/*/NEWS.*
    - usr/share/doc/*/TODO.*
  test:
    fedora-30:
      image: appimagecrafters/tests-env:fedora-30
      command: ./AppRun
      use_host_x: true
    debian-stable:
      image: appimagecrafters/tests-env:debian-stable
      command: ./AppRun
      use_host_x: true
    archlinux-latest:
      image: appimagecrafters/tests-env:archlinux-latest
      command: ./AppRun
      use_host_x: true
    centos-7:
      image: appimagecrafters/tests-env:centos-7
      command: ./AppRun
      use_host_x: true
    ubuntu-xenial:
      image: appimagecrafters/tests-env:ubuntu-xenial
      command: ./AppRun
      use_host_x: true
AppImage:
  arch: x86_64
  update-information: guess
```
