### ISSUE TITLE
How to check XDG_CACHE_HOME 

### ISSUE THREAD

**Issue by TIS-Edgar** [AppImageCrafters/appimage-builder#167]
Hi,

I want to write a cache file to speed up later runs of the appimage.
For this I want to check XDG_CACHE_HOME and have a fallback variable for when it is not set.

In bash the check would look like this:

     echo ${XDG_CACHE_HOME:-$HOME/.cache}

Documentation for this is here: https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html

Setting that in the recipe results in wrong path descriptions.
```
    runtime:
      path_mappings:
        - /dev/:$APPDIR/dev
      env:
        GST_PLUGIN_SYSTEM_PATH_1_0: '${APPDIR}/usr/lib/@CMAKE_SYSTEM_PROCESSOR@-linux-gnu/gstreamer-1.0' 
        GST_REGISTRY: "${XDG_CACHE_HOME:-$HOME/.cache}/application/gstreamer-cache.bin"
```

That writes to `/home/user/-/home/user/.cache/application/`. Is there a way to have such a check or is it simply impossible?
