### ISSUE TITLE
Could not find 'pacman-key' on $PATH. while building flutter app on ubuntu 20.04

### ISSUE THREAD

**Issue by atul-chaudhary** [AppImageCrafters/appimage-builder#169]
Urgent :+1: 
Tried generating the appImage using ```appimage-builder --recipe AppImageBuilder.yml``` for flutter app, but got the error
```
INFO:main:Running pacman deploy
Traceback (most recent call last):
  File "/usr/local/bin/appimage-builder", line 8, in <module>
    sys.exit(__main__())
  File "/usr/local/lib/python3.8/dist-packages/appimagebuilder/__main__.py", line 58, in __main__
    invoker.execute(commands)
  File "/usr/local/lib/python3.8/dist-packages/appimagebuilder/invoker.py", line 41, in execute
    command()
  File "/usr/local/lib/python3.8/dist-packages/appimagebuilder/commands/pacman_deploy.py", line 42, in __call__
    venv = Venv(
  File "/usr/local/lib/python3.8/dist-packages/appimagebuilder/modules/deploy/pacman/venv.py", line 57, in __init__
    self._deps = shell.resolve_commands_paths(DEPENDS_ON)
  File "/usr/local/lib/python3.8/dist-packages/appimagebuilder/utils/shell.py", line 23, in resolve_commands_paths
    raise CommandNotFoundError(
appimagebuilder.utils.shell.CommandNotFoundError: Could not find 'pacman-key' on $PATH.

```

I know we use pacman on arch linux, Since I'm using the```ubuntu 20.04```, not sure why i'm getting this error. I'm following the official documentation for creating the appImage for flutter apps [link](https://appimage-builder.readthedocs.io/en/latest/examples/flutter.html)

here is my recepie
```
# appimage-builder recipe see https://appimage-builder.readthedocs.io for details
version: 1
script:
  - rm -rf AppDir || true
  - cp -r build/linux/x64/release/bundle AppDir
  - mkdir -p AppDir/usr/share/icons/hicolor/64x64/apps/
  - cp blup_logo.svg AppDir/usr/share/icons/hicolor/64x64/apps/
AppDir:
  path: /home/atul/StudioProjects/Blup/ide/AppDir
  app_info:
    id: in.blup
    name: blup
    icon: blup_logo
    version: 1.0.0001
    exec: example
    exec_args: $@
  apt:
    arch:
    - amd64
    allow_unauthenticated: true
    sources:
    - sourceline: deb http://in.archive.ubuntu.com/ubuntu/ focal main restricted
    - sourceline: deb http://in.archive.ubuntu.com/ubuntu/ focal-updates main restricted
    - sourceline: deb http://in.archive.ubuntu.com/ubuntu/ focal universe
    - sourceline: deb http://in.archive.ubuntu.com/ubuntu/ focal-updates universe
    - sourceline: deb http://in.archive.ubuntu.com/ubuntu/ focal multiverse
    - sourceline: deb http://in.archive.ubuntu.com/ubuntu/ focal-updates multiverse
    - sourceline: deb http://in.archive.ubuntu.com/ubuntu/ focal-backports main restricted
        universe multiverse
    - sourceline: deb http://security.ubuntu.com/ubuntu focal-security main restricted
    - sourceline: deb http://security.ubuntu.com/ubuntu focal-security universe
    - sourceline: deb http://security.ubuntu.com/ubuntu focal-security multiverse
    - sourceline: deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable
        main
    - sourceline: deb [arch=amd64] https://packagecloud.io/shiftkey/desktop/any/ any
        main
    - sourceline: deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg
        arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main
    - sourceline: deb [arch=amd64,arm64,armhf] http://packages.microsoft.com/repos/code
        stable main
    include:
    - brave-browser
    - desktop-file-utils
    - fonts-dejavu-core
    - fonts-noto-color-emoji
    - fonts-ubuntu
    - glib-networking:amd64
    - gvfs:amd64
    - language-pack-gnome-en-base
    - libasound2-data
    - libasound2-plugins:amd64
    - libbz2-1.0:amd64
    - libcanberra-gtk3-module:amd64
    - libcom-err2:amd64
    - libgtk-3-common
    - libidn11:amd64
    - libkeyutils1:amd64
    - liblzma5:amd64
    - libmount1:amd64
    - libnss-mdns:amd64
    - libnvidia-gl-470:amd64
    - libpcre3:amd64
    - libproxy1-plugin-gsettings:amd64
    - libproxy1-plugin-networkmanager:amd64
    - libsystemd0:amd64
    - libuuid1:amd64
    - transmission-common
    - vlc-plugin-base:amd64
    - yaru-theme-gtk
    - yaru-theme-icon
  pacman:
    include: []
    exclude: []
  files:
    include:
    - /home/atul/.local/share/applications/mimeapps.list
    - /home/atul/.local/share/com.example.example/CourierPrime_regular.ttf
    - /home/atul/.local/share/com.example.example/iml
    - /home/atul/.local/share/com.example.example/shared_preferences.json
    - /home/atul/Documents/Blup/Saved Projects/sasa.blup
    - /lib/x86_64-linux-gnu/libEGL_mesa.so.0
    - /lib/x86_64-linux-gnu/libEGL_nvidia.so.0
    - /lib/x86_64-linux-gnu/libFLAC.so.8
    - /lib/x86_64-linux-gnu/libGLX.so.0
    - /lib/x86_64-linux-gnu/libGLdispatch.so.0
    - /lib/x86_64-linux-gnu/libLLVM-12.so.1
    - /lib/x86_64-linux-gnu/libOpenCL.so.1
    - /lib/x86_64-linux-gnu/libOpenGL.so.0
    - /lib/x86_64-linux-gnu/libX11.so.6
    - /lib/x86_64-linux-gnu/libXau.so.6
    - /lib/x86_64-linux-gnu/libXcomposite.so.1
    - /lib/x86_64-linux-gnu/libXcursor.so.1
    - /lib/x86_64-linux-gnu/libXdamage.so.1
    - /lib/x86_64-linux-gnu/libXdmcp.so.6
    - /lib/x86_64-linux-gnu/libXext.so.6
    - /lib/x86_64-linux-gnu/libXfixes.so.3
    - /lib/x86_64-linux-gnu/libXi.so.6
    - /lib/x86_64-linux-gnu/libXinerama.so.1
    - /lib/x86_64-linux-gnu/libXrandr.so.2
    - /lib/x86_64-linux-gnu/libXrender.so.1
    - /lib/x86_64-linux-gnu/libXxf86vm.so.1
    - /lib/x86_64-linux-gnu/libacl.so.1
    - /lib/x86_64-linux-gnu/libaom.so.0
    - /lib/x86_64-linux-gnu/libapparmor.so.1
    - /lib/x86_64-linux-gnu/libarchive.so.13
    - /lib/x86_64-linux-gnu/libasound.so.2
    - /lib/x86_64-linux-gnu/libasyncns.so.0
    - /lib/x86_64-linux-gnu/libatk-1.0.so.0
    - /lib/x86_64-linux-gnu/libatk-bridge-2.0.so.0
    - /lib/x86_64-linux-gnu/libatspi.so.0
    - /lib/x86_64-linux-gnu/libavahi-client.so.3
    - /lib/x86_64-linux-gnu/libavahi-common.so.3
    - /lib/x86_64-linux-gnu/libavcodec.so.58
    - /lib/x86_64-linux-gnu/libavutil.so.56
    - /lib/x86_64-linux-gnu/libbrotlicommon.so.1
    - /lib/x86_64-linux-gnu/libbrotlidec.so.1
    - /lib/x86_64-linux-gnu/libbsd.so.0
    - /lib/x86_64-linux-gnu/libcairo-gobject.so.2
    - /lib/x86_64-linux-gnu/libcairo.so.2
    - /lib/x86_64-linux-gnu/libcanberra-gtk3.so.0
    - /lib/x86_64-linux-gnu/libcanberra.so.0
    - /lib/x86_64-linux-gnu/libcodec2.so.0.9
    - /lib/x86_64-linux-gnu/libcups.so.2
    - /lib/x86_64-linux-gnu/libdatrie.so.1
    - /lib/x86_64-linux-gnu/libedit.so.2
    - /lib/x86_64-linux-gnu/libelf.so.1
    - /lib/x86_64-linux-gnu/libenchant-2.so.2
    - /lib/x86_64-linux-gnu/libepoxy.so.0
    - /lib/x86_64-linux-gnu/libfaad.so.2
    - /lib/x86_64-linux-gnu/libffi.so.7
    - /lib/x86_64-linux-gnu/libfontconfig.so.1
    - /lib/x86_64-linux-gnu/libfreetype.so.6
    - /lib/x86_64-linux-gnu/libfribidi.so.0
    - /lib/x86_64-linux-gnu/libgbm.so.1
    - /lib/x86_64-linux-gnu/libgcrypt.so.20
    - /lib/x86_64-linux-gnu/libgdk-3.so.0
    - /lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0
    - /lib/x86_64-linux-gnu/libgio-2.0.so
    - /lib/x86_64-linux-gnu/libgio-2.0.so.0
    - /lib/x86_64-linux-gnu/libglapi.so.0
    - /lib/x86_64-linux-gnu/libglib-2.0.so.0
    - /lib/x86_64-linux-gnu/libgmodule-2.0.so.0
    - /lib/x86_64-linux-gnu/libgmp.so.10
    - /lib/x86_64-linux-gnu/libgnutls.so.30
    - /lib/x86_64-linux-gnu/libgobject-2.0.so.0
    - /lib/x86_64-linux-gnu/libgomp.so.1
    - /lib/x86_64-linux-gnu/libgraphite2.so.3
    - /lib/x86_64-linux-gnu/libgsm.so.1
    - /lib/x86_64-linux-gnu/libgssapi_krb5.so.2
    - /lib/x86_64-linux-gnu/libgstallocators-1.0.so.0
    - /lib/x86_64-linux-gnu/libgstapp-1.0.so.0
    - /lib/x86_64-linux-gnu/libgstaudio-1.0.so.0
    - /lib/x86_64-linux-gnu/libgstbase-1.0.so.0
    - /lib/x86_64-linux-gnu/libgstfft-1.0.so.0
    - /lib/x86_64-linux-gnu/libgstgl-1.0.so.0
    - /lib/x86_64-linux-gnu/libgstpbutils-1.0.so.0
    - /lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
    - /lib/x86_64-linux-gnu/libgsttag-1.0.so.0
    - /lib/x86_64-linux-gnu/libgstvideo-1.0.so.0
    - /lib/x86_64-linux-gnu/libgtk-3.so.0
    - /lib/x86_64-linux-gnu/libgudev-1.0.so.0
    - /lib/x86_64-linux-gnu/libharfbuzz-icu.so.0
    - /lib/x86_64-linux-gnu/libharfbuzz.so.0
    - /lib/x86_64-linux-gnu/libhogweed.so.5
    - /lib/x86_64-linux-gnu/libhyphen.so.0
    - /lib/x86_64-linux-gnu/libicudata.so.66
    - /lib/x86_64-linux-gnu/libicui18n.so.66
    - /lib/x86_64-linux-gnu/libicuuc.so.66
    - /lib/x86_64-linux-gnu/libidn2.so.0
    - /lib/x86_64-linux-gnu/libjavascriptcoregtk-4.0.so.18
    - /lib/x86_64-linux-gnu/libjpeg.so.8
    - /lib/x86_64-linux-gnu/libk5crypto.so.3
    - /lib/x86_64-linux-gnu/libkrb5.so.3
    - /lib/x86_64-linux-gnu/libkrb5support.so.0
    - /lib/x86_64-linux-gnu/liblcms2.so.2
    - /lib/x86_64-linux-gnu/libltdl.so.7
    - /lib/x86_64-linux-gnu/liblua5.2.so.0
    - /lib/x86_64-linux-gnu/liblz4.so.1
    - /lib/x86_64-linux-gnu/libmp3lame.so.0
    - /lib/x86_64-linux-gnu/libnettle.so.7
    - /lib/x86_64-linux-gnu/libnotify.so.4
    - /lib/x86_64-linux-gnu/libnspr4.so
    - /lib/x86_64-linux-gnu/libnss3.so
    - /lib/x86_64-linux-gnu/libnssutil3.so
    - /lib/x86_64-linux-gnu/libnuma.so.1
    - /lib/x86_64-linux-gnu/libnvidia-eglcore.so.470.57.02
    - /lib/x86_64-linux-gnu/libnvidia-glsi.so.470.57.02
    - /lib/x86_64-linux-gnu/libogg.so.0
    - /lib/x86_64-linux-gnu/libopenjp2.so.7
    - /lib/x86_64-linux-gnu/libopus.so.0
    - /lib/x86_64-linux-gnu/liborc-0.4.so.0
    - /lib/x86_64-linux-gnu/libp11-kit.so.0
    - /lib/x86_64-linux-gnu/libpango-1.0.so.0
    - /lib/x86_64-linux-gnu/libpangocairo-1.0.so.0
    - /lib/x86_64-linux-gnu/libpangoft2-1.0.so.0
    - /lib/x86_64-linux-gnu/libpci.so.3
    - /lib/x86_64-linux-gnu/libpcre2-8.so.0
    - /lib/x86_64-linux-gnu/libpixman-1.so.0
    - /lib/x86_64-linux-gnu/libplc4.so
    - /lib/x86_64-linux-gnu/libplds4.so
    - /lib/x86_64-linux-gnu/libpng16.so.16
    - /lib/x86_64-linux-gnu/libproxy.so.1
    - /lib/x86_64-linux-gnu/libpsl.so.5
    - /lib/x86_64-linux-gnu/libpulse.so.0
    - /lib/x86_64-linux-gnu/librsvg-2.so.2
    - /lib/x86_64-linux-gnu/libseccomp.so.2
    - /lib/x86_64-linux-gnu/libsecret-1.so.0
    - /lib/x86_64-linux-gnu/libsensors.so.5
    - /lib/x86_64-linux-gnu/libshine.so.3
    - /lib/x86_64-linux-gnu/libsmime3.so
    - /lib/x86_64-linux-gnu/libsnappy.so.1
    - /lib/x86_64-linux-gnu/libsndfile.so.1
    - /lib/x86_64-linux-gnu/libsoup-2.4.so.1
    - /lib/x86_64-linux-gnu/libsoxr.so.0
    - /lib/x86_64-linux-gnu/libspeex.so.1
    - /lib/x86_64-linux-gnu/libsqlite3.so
    - /lib/x86_64-linux-gnu/libsqlite3.so.0
    - /lib/x86_64-linux-gnu/libstdc++.so.6
    - /lib/x86_64-linux-gnu/libswresample.so.3
    - /lib/x86_64-linux-gnu/libtag.so.1
    - /lib/x86_64-linux-gnu/libtasn1.so.6
    - /lib/x86_64-linux-gnu/libtdb.so.1
    - /lib/x86_64-linux-gnu/libthai.so.0
    - /lib/x86_64-linux-gnu/libtheoradec.so.1
    - /lib/x86_64-linux-gnu/libtheoraenc.so.1
    - /lib/x86_64-linux-gnu/libtwolame.so.0
    - /lib/x86_64-linux-gnu/libunistring.so.2
    - /lib/x86_64-linux-gnu/libva-drm.so.2
    - /lib/x86_64-linux-gnu/libva-x11.so.2
    - /lib/x86_64-linux-gnu/libva.so.2
    - /lib/x86_64-linux-gnu/libvdpau.so.1
    - /lib/x86_64-linux-gnu/libvlc.so.5
    - /lib/x86_64-linux-gnu/libvlccore.so.9
    - /lib/x86_64-linux-gnu/libvorbis.so.0
    - /lib/x86_64-linux-gnu/libvorbisenc.so.2
    - /lib/x86_64-linux-gnu/libvorbisfile.so.3
    - /lib/x86_64-linux-gnu/libvpx.so.6
    - /lib/x86_64-linux-gnu/libvulkan.so.1
    - /lib/x86_64-linux-gnu/libwavpack.so.1
    - /lib/x86_64-linux-gnu/libwayland-client.so.0
    - /lib/x86_64-linux-gnu/libwayland-cursor.so.0
    - /lib/x86_64-linux-gnu/libwayland-egl.so.1
    - /lib/x86_64-linux-gnu/libwayland-server.so.0
    - /lib/x86_64-linux-gnu/libwebkit2gtk-4.0.so.37
    - /lib/x86_64-linux-gnu/libwebp.so.6
    - /lib/x86_64-linux-gnu/libwebpdemux.so.2
    - /lib/x86_64-linux-gnu/libwebpmux.so.3
    - /lib/x86_64-linux-gnu/libwoff2common.so.1.0.2
    - /lib/x86_64-linux-gnu/libwoff2dec.so.1.0.2
    - /lib/x86_64-linux-gnu/libwrap.so.0
    - /lib/x86_64-linux-gnu/libx264.so.155
    - /lib/x86_64-linux-gnu/libx265.so.179
    - /lib/x86_64-linux-gnu/libxcb-dri2.so.0
    - /lib/x86_64-linux-gnu/libxcb-dri3.so.0
    - /lib/x86_64-linux-gnu/libxcb-present.so.0
    - /lib/x86_64-linux-gnu/libxcb-sync.so.1
    - /lib/x86_64-linux-gnu/libxkbcommon.so.0
    - /lib/x86_64-linux-gnu/libxml2.so.2
    - /lib/x86_64-linux-gnu/libxshmfence.so.1
    - /lib/x86_64-linux-gnu/libxslt.so.1
    - /lib/x86_64-linux-gnu/libxvidcore.so.4
    - /lib/x86_64-linux-gnu/libzstd.so.1
    - /lib/x86_64-linux-gnu/libzvbi.so.0
    - /usr/lib/locale/locale-archive
    - /usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules.cache
    - /usr/lib/x86_64-linux-gnu/vlc/plugins/plugins.dat
    - /usr/share//mime//mime.cache
    - /usr/share/applications/mimeinfo.cache
    - /var/lib/snapd/desktop/applications/mimeinfo.cache
    - fonts/CircularStd-Bold.otf
    - fonts/Graphik-Bold.otf
    - fonts/Graphik-Condensed-Regular.otf
    - fonts/Graphik-Medium.otf
    - fonts/Graphik-Regular.otf
    - fonts/Graphik-Wide-Medium.otf
    - fonts/Graphik-Wide-Regular.otf
    - images/bd_info_rect_2.png
    - images/bd_info_text_2.png
    - images/bd_info_wid_lib_2.png
    - images/elli_orange_crop.png
    - images/elli_pink_crop.png
    - images/fileOpenCreateBg.png
    - images/help_blupsheets.gif
    - images/help_rect.gif
    - images/help_text.gif
    - images/list.png
    - images/live_chat.png
    - images/logo.png
    - images/peach.jpg
    - images/project_app.png
    exclude:
    - usr/share/man
    - usr/share/doc/*/README.*
    - usr/share/doc/*/changelog.*
    - usr/share/doc/*/NEWS.*
    - usr/share/doc/*/TODO.*
  test:
    fedora-30:
      image: appimagecrafters/tests-env:fedora-30
      command: ./AppRun
      use_host_x: true
    debian-stable:
      image: appimagecrafters/tests-env:debian-stable
      command: ./AppRun
      use_host_x: true
    archlinux-latest:
      image: appimagecrafters/tests-env:archlinux-latest
      command: ./AppRun
      use_host_x: true
    centos-7:
      image: appimagecrafters/tests-env:centos-7
      command: ./AppRun
      use_host_x: true
    ubuntu-xenial:
      image: appimagecrafters/tests-env:ubuntu-xenial
      command: ./AppRun
      use_host_x: true
AppImage:
  arch: x86_64
  update-information: guess

```
 
this Issue is increasing the time for your app launch.
