### ISSUE TITLE
C application - system calls 

### ISSUE THREAD

**Issue by fanisatt** [AppImageCrafters/appimage-builder#171]
I have developed my own application written in C language (Pedaba - Pedaba 2.5).  The operation of my initial executable file depends on a special graphics library.  So , I needed to make an application image with your tool , in order to integrate this library, so that the user does not have to install it. 
I created the appimage with appimage-builder in kubuntu 20. The appimage is running good only in kubuntu 20 - ubuntu 20 and linux mint 20 but, not normally in older distros (like Mint 18.3 or Kubuntu 18). It is not running normally even in the modern MX Linux 21 (Debian based).
By saying that the appimage does not run normally I mean that, it presents only one specific problem (but critical for my application functionality) !!!
There is no problem at all with the graphics library integration in any linux distro I have tried !!!! The problem is that system calls to external applications do not work. (system calls to external applications are absolutely ok only in the three distros I have already report).  
I use "popen" and "fork - execl" C commands in my C code (depending on the need) to make the necessary system calls through my C application.   
Let's simplify things !!

Ι enclose the following very small C code to demonstrate the problem ...
 
#include<stdio.h>
#include<time.h>
#include<ctype.h>
#include<string.h>
#include<stdlib.h>
#include<unistd.h>
#include <memory.h>
#include <pwd.h>
#include <errno.h>
#include<sys/wait.h>

int main()
{
pid_t pid ;
int a=0 ,ch , status ;
char string [1024] ;
FILE *fpout ;
        
        strcpy (string,"https://www.youtube.com");
        printf("%s","Please hit \'q\' to make a system call for Firefox : ");
        ch=getc(stdin);
        printf ("%c\n", (char) ch);
        if (ch!='q') goto GOOD_DAY ;
        
        pid = fork();

        if (pid<0) {perror("Sorry Fork...");}
        else if (pid==0) {
            execl("/usr/bin/firefox","firefox", string ,(char *)NULL); 
            _exit(1);
        }
        else {waitpid(pid,&status,WNOHANG);}
                        
        if (status==-1) {perror("..any other error.. ");}
        
GOOD_DAY :

        printf("Bye\n");

        exit (0);
}

I made the typical executable with gcc ! It is working normally in any distro I tried .
After this I made the corresponding appimage with appimage-builder in Kubuntu 20.
The generated appimage is working normally only in Kubuntu 20 - Ubuntu 20 and Mint 20.
In other linux distros the system call to the "firefox" application fails. Anyway it does nothing....

Any help please ??
Many Thanks for your splendid tool !

**Comment by fanisatt** [comment]
Thanks @azubieta , I shall wait for the fix !
Best Regards !!

**Comment by fanisatt** [comment]
> Hello, `exec` calls are intercepted by lipapprun_hooks which basically overrides paths if a mapping is set. Your issue may be because of a bug there. As quick fix If your application doesn't required any kind of path mapping you can remove the binary `libapprun_hooks.so`. Otherwise we will have to make a fix on [libapprun](https://github.com/AppImageCrafters/AppRun)

Hello @azubieta  , I can't understand how I can remove the binary libapprun_hooks.so !! Any help ?

**Comment by azubieta** [comment]
Many things could be happening here. The packages made by appimage-builder are not completely independent or self-contained they do use certain libraries from the host system therefore some libs you bundle may not get along with the ones in the target systems therefore the issue.

Could you please create a recipe for you POC so we could check it out together.

**Comment by fanisatt** [comment]
Hello Alexis.  I think we need to simplify the situation at this stage . I do not see an "indefinite" problem where many things may be happening. The application image is running normally in MX_21 too but ... there is  ONLY one (critical) problem :  the (external) calls are not executed (I mean the system calls with the standard C functions popen / excecl). The problem to me is absolutely specific !! This is the reason I wrote in my first comment here the very small C program.  It is fine to demonstrate the problem.  I guess this situation will apply to other modern operating systems too . (I first saw it happens in older versions of  popular distros (like Ubuntu 18 - Mint 18 ), but I did not expect it to happen in a more modern one like MX_21) In addition , I noticed that , although MX_21 is a DEBIAN based distro, I can not even create an application image there. Anyway this is not a serious problem because I use Ubuntu 20 to create appimages with your tool. Please try to simplify the situation at this stage, I am sure  that it will be easily solved by you when you try the C (demo) code I wrote initially here. Many Thanks !!!!

**Comment by azubieta** [comment]
@fanisatt maybe I didn't understood your words the first time. Take your mock into an AppImage and make the tests.

**Comment by fanisatt** [comment]
I tried to be completely clear about the problem. I use your tool my friend and I am very happy because the appimage works perfectly on many Linux operating systems. My applications use sdl libraries. The versions of  these libraries  are very advanced in some OSs  such as fedora or arch or slackware , (in relation to the versions in Ubuntu 20 - Mint 20) and the result is that my applications don't run everywhere , except in the form of appimage . So .... I only thank you for this tool , there is not any mock , perhaps my english is bad but I repeat , there is not any mock , it is simply a real issue I can't handle here.   Best Regards !

**Comment by azubieta** [comment]
Hello @fanisatt, could you please give a try to the v1.0.0-alpha.1 release of appimage-builder? It uses a new AppRun with `execl` hooks.

**Comment by fanisatt** [comment]
Hello Alexis , I will try it these days ! Thanks !

**Comment by fanisatt** [comment]
Hello again Alexis, please tell me if I have to install the development version to try it : sudo pip3 install git+https://github.com/AppImageCrafters/appimage-builder.git ? I tried today with the latest tagged release but the problem remains.

**Comment by fanisatt** [comment]
Hello Alexis , I installed the development version (alpha release) and I tried again but the problem remains.  Anyway , I don't know if it is an MX Linux particularity !!! The AppImage is working perfectly in other great Linux OSs like Fedora , Arch , Mint , Ubuntu , Kubuntu and I mean  the official version of your tool that I have already used  (not the alpha release I tried today) ! MX Linux is a DEBIAN based distro but, unfortunately I don't have any DEBIAN OS installed here to give it a shot . Best Regards !!!

**Comment by azubieta** [comment]
I've been trying a variation of your code with debian stable and latest and it works as expected using the latest AppImageBuilder. 

Did you know (or can create) a mx-linux docker image?

**Comment by fanisatt** [comment]
These are very-very good news my friend !!! The possibility that this issue is a peculiarity / particularity  of the MX Linux  is greatly enhanced to my opinion .  Possibly I have to somehow ask the MX Linux team about it. It may be (somehow) a matter of  user "rights" .... or something anyway... I really can't imagine what is it. Unfortunately I don't know how to create docker images. Never mind !!! Keep up your good work !! Best Regards !

**Comment by azubieta** [comment]
Don't worry about the docker image, it took me about an hour but I finally download the MXLinux installer, will try it and give you feedback.

**Comment by fanisatt** [comment]
Very kind of you Alexis !!! Thank you very much !

**Comment by azubieta** [comment]
It seems that the problem is fixed I just built this: https://transfer.sh/bL3HNW/app-latest-x86_64.AppImage
using the latest appimage-builder in MXLinux

Here is the recipe I used
```
# appimage-builder recipe see https://appimage-builder.readthedocs.io for details
version: 1
script:
 - rm -rf $TARGET_APPDIR || true
 - mkdir -p $TARGET_APPDIR/bin
 - cp a.out $TARGET_APPDIR/bin/app
AppDir:
  path: /home/mxlinux/AppDir
  app_info:
    id: app
    name: app
    icon: application-vnd.appimage
    version: latest
    exec: bin/app
    exec_args: $@
  apt:
    arch:
    - amd64
    allow_unauthenticated: true
    sources:
    - sourceline: deb http://deb.debian.org/debian bullseye-updates main contrib non-free
    - sourceline: deb http://mirrors.rit.edu/mxlinux/mx-packages/mx/repo/ bullseye
        main non-free
    - sourceline: deb http://deb.debian.org/debian bullseye main contrib non-free
    - sourceline: deb http://security.debian.org/debian-security bullseye-security
        main contrib non-free
    include:
    - libc6
  files:
    exclude:
    - usr/share/man
    - usr/share/doc/*/README.*
    - usr/share/doc/*/changelog.*
    - usr/share/doc/*/NEWS.*
    - usr/share/doc/*/TODO.*
  test:
    fedora-30:
      image: appimagecrafters/tests-env:fedora-30
      command: ./AppRun
    debian-stable:
      image: appimagecrafters/tests-env:debian-stable
      command: ./AppRun
    archlinux-latest:
      image: appimagecrafters/tests-env:archlinux-latest
      command: ./AppRun
    centos-7:
      image: appimagecrafters/tests-env:centos-7
      command: ./AppRun
    ubuntu-xenial:
      image: appimagecrafters/tests-env:ubuntu-xenial
      command: ./AppRun
AppImage:
  arch: x86_64
  update-information: guess

```

Please feel free to reopen if needed.
