### ISSUE TITLE
Python modules not found

### ISSUE THREAD

**Issue by sr71684** [AppImageCrafters/appimage-builder#185]
I build the vanilla [PyQt5 application example](https://appimage-builder.readthedocs.io/en/latest/examples/pyqt.html) by calling `appimage-builder` in the example root.

The image appears to compile ok, however when I run `./python\ appimage\ hello\ world-0.1.0-x86_64.AppImage` the following error is encountered. 

```
Traceback (most recent call last):
  File "/tmp/.mount_python8OIMVn//usr/src/main.py", line 7, in <module>
    from pyfiglet import Figlet
ModuleNotFoundError: No module named 'pyfiglet'

```

I tried modifying the AppImageBuilder.yml recipe to Install dependencies using the embed python. Specifically, I appended the `after_bundle` block as per the PyQt5 documentation example found [here](https://appimage-builder.readthedocs.io/en/latest/examples/pyqt.html).
```
version: 1
script:
  # Remove any previous build
  - rm -rf AppDir  | true
  # Make usr and icons dirs
  - mkdir -p AppDir/usr/src
  # Copy the python application code into the AppDir
  - cp main.py  AppDir/usr/src -r

AppDir:
  path: ./AppDir

  after_bundle: |
    # Set python 3.9 env
    export PYTHONHOME=${APPDIR}/usr
    export PYTHONPATH=${APPDIR}/usr/lib/python3.9/site-packages:$APPDIR/usr/lib/python3.9
    export PATH=${APPDIR}/usr/bin:$PATH
    # Set python 3.9 as default
    ln -fs python3.9 $APPDIR/usr/bin/python3
    # Install pip
    curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
    python3.9 get-pip.py
    # Install pipenv
    python3.9 -m pip install pipenv
    # Generate the requirements.txt file
    python3.9 -m pipenv lock -r > requirements.txt
    # Install application dependencies in AppDir
    python3.9 -m pip install --upgrade --isolated --no-input --ignore-installed --prefix=$APPDIR/usr wheel
    python3.9 -m pip install --upgrade --isolated --no-input --ignore-installed --prefix=$APPDIR/usr -r ./requirements.txt

  app_info:
    id: org.appimage-crafters.python-appimage-example
    name: python appimage hello world
    icon: utilities-terminal
    version: 0.1.0
    # Set the python executable as entry point
    exec: usr/bin/python3
    # Set the application main script path as argument. Use '$@' to forward CLI parameters
    exec_args: "$APPDIR/usr/src/main.py $@"

  apt:
    arch: amd64
    sources:
      - sourceline: 'deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ focal main restricted universe multiverse'
        key_url: 'http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3b4fe6acc0b21f32'

    include:
      - python3
      - python3-pkg-resources
      - python3-pyqt5
      - libfreetype6
      - libfontconfig1
    exclude: []

  runtime:
    version: "continuous"
    env:
      PATH: '${APPDIR}/usr/bin:${PATH}'
      # Set python home
      # See https://docs.python.org/3/using/cmdline.html#envvar-PYTHONHOME
      PYTHONHOME: '${APPDIR}/usr'
      # Path to the site-packages dir or other modules dirs
      # See https://docs.python.org/3/using/cmdline.html#envvar-PYTHONPATH
      PYTHONPATH: '${APPDIR}/usr/lib/python3.8/site-packages'

AppImage:
  update-information: 'gh-releases-zsync|AppImageCrafters|python-appimage-example|latest|python-appimage-*x86_64.AppImage.zsync'
  sign-key: None
  arch: x86_64
```
but obtain the following error:

```
...
INFO:AptPackageDeploy:Deploying libpython3.6-stdlib_3.6.5-3_amd64.deb to /home/jack/dev/da-bridge/AppDir
INFO:AptPackageDeploy:Deploying libpython3.6-minimal_3.6.5-3_amd64.deb to /home/jack/dev/da-bridge/AppDir
INFO:AptPackageDeploy:Deploying libmpdec2_2.4.2-1ubuntu1_amd64.deb to /home/jack/dev/da-bridge/AppDir
INFO:main:Running after bundle script
# Set python 3.9 env
export PYTHONHOME=${APPDIR}/usr/lib/python3.9/site-packages:$APPDIR/usr/lib/python3.9
export PYTHONPATH=${APPDIR}/usr/lib/python3.9/site-packages:$APPDIR/usr/lib/python3.9
#export PATH=${APPDIR}/usr/bin:$PATH
# Set python 3.9 as default
ln -fs python3.9 $APPDIR/usr/bin/python3.9
# Install pip
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2548k  100 2548k    0     0  18.0M      0 --:--:-- --:--:-- --:--:-- 18.0M
python3.9 get-pip.py
Python path configuration:
  PYTHONHOME = '/home/jack/dev/da-bridge/AppDir/usr/lib/python3.9/site-packages:/home/jack/dev/da-bridge/AppDir/usr/lib/python3.9'
  PYTHONPATH = '/home/jack/dev/da-bridge/AppDir/usr/lib/python3.9/site-packages:/home/jack/dev/da-bridge/AppDir/usr/lib/python3.9'
  program name = 'python3.9'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = '/home/jack/anaconda3/envs/da-bridge/bin/python3.9'
  sys.base_prefix = '/home/jack/dev/da-bridge/AppDir/usr/lib/python3.9/site-packages'
  sys.base_exec_prefix = '/home/jack/dev/da-bridge/AppDir/usr/lib/python3.9'
  sys.platlibdir = 'lib'
  sys.executable = '/home/jack/anaconda3/envs/da-bridge/bin/python3.9'
  sys.prefix = '/home/jack/dev/da-bridge/AppDir/usr/lib/python3.9/site-packages'
  sys.exec_prefix = '/home/jack/dev/da-bridge/AppDir/usr/lib/python3.9'
  sys.path = [
    '/home/jack/dev/da-bridge/AppDir/usr/lib/python3.9/site-packages',
    '/home/jack/dev/da-bridge/AppDir/usr/lib/python3.9',
    '/home/jack/dev/da-bridge/AppDir/usr/lib/python3.9/site-packages/lib/python39.zip',
    '/home/jack/dev/da-bridge/AppDir/usr/lib/python3.9/site-packages/lib/python3.9',
    '/home/jack/dev/da-bridge/AppDir/usr/lib/python3.9/lib/python3.9/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007f7d250d6300 (most recent call first):
<no Python frame>
Traceback (most recent call last):
  File "/home/jack/anaconda3/envs/da-bridge/bin/appimage-builder", line 8, in <module>
    sys.exit(__main__())
  File "/home/jack/anaconda3/envs/da-bridge/lib/python3.9/site-packages/appimagebuilder/__main__.py", line 58, in __main__
    invoker.execute(commands)
  File "/home/jack/anaconda3/envs/da-bridge/lib/python3.9/site-packages/appimagebuilder/invoker.py", line 41, in execute
    command()
  File "/home/jack/anaconda3/envs/da-bridge/lib/python3.9/site-packages/appimagebuilder/commands/run_shell_script.py", line 64, in __call__
    raise RuntimeError("Script exited with code: %s" % _proc.returncode)
RuntimeError: Script exited with code: 1

```

**OS**: 21.10 Ubuntu
