### ISSUE TITLE
Qt6 not working

### ISSUE THREAD

**Issue by Paullux** [AppImageCrafters/appimage-builder#198]
I am on Jammy Ubuntu, I create an AppImage with appimage-builder --recipe AppImageBuilder.yml

my AppImageBuilder.yml is :
```yml
# appimage-builder recipe see https://appimage-builder.readthedocs.io for details
version: 1
script: |
  # remove any existent binaries
  rm -rf AppDir | true

  # compile and install binaries into AppDir
  cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
  make install DESTDIR=AppDir
AppDir:
  path: ./AppDir
  app_info:
    id: francetv
    name: FranceTV
    icon: france-tv
    version: '1.0'
    exec: usr/bin/FranceTV
    exec_args: $@
  runtime:
    env:
      # Disable webengine sandboxing
      QTWEBENGINE_DISABLE_SANDBOX: 0
      QT_QPA_PLATFORM: xcb
  apt:
    arch: amd64
    allow_unauthenticated: true
    sources:
      - sourceline: deb http://fr.archive.ubuntu.com/ubuntu/ jammy main restricted
      - sourceline: deb http://fr.archive.ubuntu.com/ubuntu/ jammy-updates main restricted
      - sourceline: deb http://fr.archive.ubuntu.com/ubuntu/ jammy universe
      - sourceline: deb http://fr.archive.ubuntu.com/ubuntu/ jammy-updates universe
      - sourceline: deb http://fr.archive.ubuntu.com/ubuntu/ jammy multiverse
      - sourceline: deb http://fr.archive.ubuntu.com/ubuntu/ jammy-updates multiverse
      - sourceline: deb http://fr.archive.ubuntu.com/ubuntu/ jammy-backports main
          restricted universe multiverse
      - sourceline: deb http://security.ubuntu.com/ubuntu jammy-security main restricted
      - sourceline: deb http://security.ubuntu.com/ubuntu jammy-security universe
      - sourceline: deb http://security.ubuntu.com/ubuntu jammy-security multiverse
    include:
      - libxkbcommon0
      - libxkbcommon-x11-0
      - libxcb-icccm4
      - libxcb-xkb1
      - libxcb-render-util0
      - libxcb-randr0
      - libxcb-keysyms1
      - libxcb-xinerama0
      - libxcb-image0
      - kwayland-data
      - kwin-wayland-backend-drm
      - kwin-wayland-backend-fbdev
      - kwin-wayland-backend-virtual
      - kwin-wayland-backend-wayland 
      - kwin-wayland-backend-x11
      - libqt6webengine6-data
      - libqt6widgets6
      - libqt6core6
      - libqcoro6core0
      - libqt6core5compat6
      - libqt6webenginecore6
      - libqt6webenginecore6
      - libqt6svg6
      - libqt6gui6
      - libqt6webview6
      - libqt6webenginewidgets6
      - libqt6webenginecore6
      - libqt6webenginecore6-bin
      - libqt6webenginequick6
      - libqt6network6
      - qt6-base-dev
      - libqt6waylandclient6
      - libqt6waylandcompositor6
      - libqt6waylandeglclienthwintegration6
      - libqt6waylandeglcompositorhwintegration6
      - qt6-wayland
    exclude: []
  files:
    include: []
    exclude:
      - usr/share/man
      - usr/share/doc/*/README.*
      - usr/share/doc/*/changelog.*
      - usr/share/doc/*/NEWS.*
      - usr/share/doc/*/TODO.*
AppImage:
  arch: x86_64
  update-information: guess
  sign-key: None
```
In my system Jammy the appimage works correctly but in other linux (x11 or wayland) i have this error :
```qt
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
```

It's a bug or It's from me ?

when i try to debug :
`qDebug() << "PluginPath is : " << QLibraryInfo::location(QLibraryInfo::PluginsPath);`
the result is :
`PluginPath is :  "/tmp/.mount_Francex0mlxO/usr/lib/x86_64-linux-gnu/qt6/plugins"`
its the correct path
