### ISSUE TITLE
FileExistsError during deploy

### ISSUE THREAD

**Issue by mirkobrombin** [AppImageCrafters/appimage-builder#205]
I was trying to build the following recipe:

```
version: 1
script:
  # Remove any previous build
  - rm -rf AppDir | true
  - rm -rf build  | true
  # Building with meson and ninja
  - mkdir build
  - meson build --prefix=/usr
  - cd build
  - ninja
  - DESTDIR=$APPDIR ninja install
  # - ninja bottles-pot
  # - ninja bottles-update-po
  - cd ..
  # Preparing directories
  - mkdir -p AppDir/usr AppDir/usr/local/share/bottles AppDir/usr/bin AppDir/usr/share/glib-2.0/schemas AppDir/usr/share/applications AppDir/usr/share/metainfo AppDir/usr/share/icons
  # Compiling and installing glib-resources
  - glib-compile-resources --sourcedir=src/ui/ src/ui/bottles.gresource.xml --target=AppDir/usr/local/share/bottles/bottles.gresource
  # Copying Bottles binary
  - cp build/src/bottles AppDir/usr/bin/
  # Copying Bottles python package and remove not useful files"
  - cp -a src AppDir/usr/local/share/bottles/bottles
  - rm AppDir/usr/local/share/bottles/bottles/bottles.in
  - rm AppDir/usr/local/share/bottles/bottles/meson.build
  # Compiling and installing translations
  - cat po/LINGUAS | while read lang
  - do
  - mkdir -p AppDir/usr/share/locale/$lang/LC_MESSAGES
  - msgfmt -o AppDir/usr/share/locale/$lang/LC_MESSAGES/bottles.mo po/$lang.po
  - done
  # Copying icons
  - cp -a data/icons AppDir/usr/share
  - mv AppDir/usr/share/icons/symbolic/scalable/apps/*.svg AppDir/usr/share/icons/hicolor/scalable/apps/
  # Copying Desktop file
  - cp build/data/com.usebottles.bottles.desktop AppDir/usr/share/applications/
  # Copying and compiling gschema
  - cp data/com.usebottles.bottles.gschema.xml AppDir/usr/share/glib-2.0/schemas/com.usebottles.bottles.gschema.xml
  - glib-compile-schemas AppDir/usr/share/glib-2.0/schemas/
  # Copying appdata
  - cp -a data/com.usebottles.bottles.appdata.xml.in AppDir/usr/share/metainfo/com.usebottles.bottles.appdata.xml
  # Set bash as default shell
  - mkdir -p $APPDIR/bin
  - ln -s bash $APPDIR/bin/sh

AppDir:
  path: ./AppDir

  app_info:
    id: com.usebottles.bottles
    name: Bottles
    icon: com.usebottles.bottles
    version: 2022.3.28-trento-1
    # Set the python executable as entry point
    exec: usr/bin/python3.9
    # Set the application main script path as argument. Use '$@' to forward CLI parameters
    exec_args: "$APPDIR/usr/bin/bottles $@"

  pacman:
    include:
      - lib32-gnutls
      - gtksourceview4
      - hicolor-icon-theme
      - dconf
      - python
      - libhandy
      - gtk3
      - p7zip
      - python-gobject
      - python-requests
      - python-yaml
      - python-markdown
      - cabextract
      - webkit2gtk
      - xorg-xdpyinfo
      - gvfs
      - vkd3d
      - lib32-vkd3d
      - lib32-vulkan-icd-loader
      - vulkan-icd-loader
      - gamemode

    exclude:
    - adwaita-icon-theme
    - humanity-icon-theme

  after_runtime: |
     rm -f $APPDIR/.bundle.yml
     rm -rf $APPDIR/usr/share/doc
     rm -rf $APPDIR/usr/share/man
     mkdir -p $APPDIR/usr/local/lib/p7zip/ 
     ln -s $APPDIR/usr/lib/p7zip/ $APPDIR/usr/local/lib/p7zip/

  files:
    include:
      - AppDir/usr/lib/x86_64-linux-gnu/libffi.so.8
      - AppDir/usr/lib/x86_64-linux-gnu/libhandy-1.so.0

    exclude:
      - AppDir/usr/lib/x86_64-linux-gnu/gconv
      - AppDir/usr/share/man
      - AppDir/usr/share/doc/*/README.*
      - AppDir/usr/share/doc/*/changelog.*
      - AppDir/usr/share/doc/*/NEWS.*
      - AppDir/usr/share/doc/*/TODO.*

  runtime:
    env:
      GDK_BACKEND: x11
      # Set python home
      PYTHONPATH: '${APPDIR}/usr/lib/python3/dist-packages'
      # SSL CERTIFICATE_VERIFY_FAILED python3.8 -m pip install --ignore-installed --prefix=/usr --root=$APPDIR install --upgrade certifi
      #SSL_CERT_DIR: "/etc/ssl/certs:/etc/pki/ca-trust/extracted/pem:/etc/pki/ca-trust/extracted/openssl:/etc/ssl:/etc/pki/tls:/etc/pki:/etc/pki/ca-trust:/usr/local/share/certs:/usr/share/pki/ca-trust-source:/etc/openssl/certs:/var/ssl/certs"
      SSL_CERT_FILE: "$APPDIR/usr/lib/python3/dist-packages/certifi/cacert.pem"
      # if you want to use Adwaita just uncomment bellow
      # GTK_THEME: Adwaita
    path_mappings:
      - /usr/share/bottles:$APPDIR/usr/local/share/bottles

AppImage:
  update-information: 'gh-releases-zsync|AppImage-*x86_64.AppImage.zsync'
  sign-key: None
  arch: x86_64
```

when the following exception was raised:
```
Traceback (most recent call last):
  File "/usr/bin/appimage-builder", line 33, in <module>
    sys.exit(load_entry_point('appimage-builder==1.0.0a3', 'console_scripts', 'appimage-builder')())
  File "/usr/lib/python3.10/site-packages/appimagebuilder/__main__.py", line 44, in __main__
    invoker.execute(commands)
  File "/usr/lib/python3.10/site-packages/appimagebuilder/invoker.py", line 29, in execute
    command()
  File "/usr/lib/python3.10/site-packages/appimagebuilder/commands/pacman_deploy.py", line 50, in __call__
    deployed_packages = pacman_deploy.deploy(
  File "/usr/lib/python3.10/site-packages/appimagebuilder/modules/deploy/pacman/deploy.py", line 87, in deploy
    os.symlink("usr/bin", appdir_root / "bin")
FileExistsError: [Errno 17] File exists: 'usr/bin' -> '/var/home/mirko/Projects/bottlesdevs/appimage/AppDir/bin'
```

ref: https://github.com/bottlesdevs/Bottles/issues/1272#issuecomment-1094120540
