### ISSUE TITLE
Python 3.10: folder `usr/local` is not included

### ISSUE THREAD

**Issue by Deuchnord** [AppImageCrafters/appimage-builder#268]
I'm trying to package my Python command-line application to an AppImage with Python 3.10 integrated, but even though it is present in the `AppDir` folder, the `usr/local` folder seems to not be included in the `AppImage`, which causes my application to fail with the error:

```
/tmp/.mount_kosmorVLpu7i/usr/bin/python3: No module named kosmorro
```

which is normal, because the module is installed from a Python Wheel package during the build.
If I run `tree` on the `AppDir` folder after the build, I can see the `usr/local` folder properly filled with my package + its dependencies, as you can see in [this GitHub Action build](https://github.com/Kosmorro/kosmorro/actions/runs/3209986852/jobs/5247114357#step:5:247) (stop _Build AppImage_ from line 246).
But if I extract the AppImage with the `APPIMAGE_EXTRACT_AND_RUN=1 NO_CLEANUP=1` environment variable, then I see the folder does not contain it.

My current build: [kosmorro.AppImage.zip](https://github.com/AppImageCrafters/appimage-builder/files/9738960/kosmorro.AppImage.zip)

My current AppImageBuilder:

```yaml
# appimage-builder recipe see https://appimage-builder.readthedocs.io for details
version: 1

script:
  - rm -rf build/AppDir | true
  - mkdir -p build/AppDir AppDir/usr/share/icons/hicolor/scalable/apps/
  - cp -r kosmorro/assets/svg/kosmorro-icon.svg  AppDir/usr/share/icons/hicolor/scalable/apps/kosmorro.svg
  - python3 -m pip install --ignore-installed --prefix=/usr --root=build/AppDir dist/kosmorro-*.whl

AppDir:
  path: build/AppDir
  app_info:
    id: space.kosmorro.cli
    name: kosmorro
    icon: kosmorro
    version: latest
    exec: usr/bin/python3
    exec_args: -m kosmorro $@

  runtime:
    env:
      PYTHONPATH: '$APPDIR/usr/local/lib/python3.10/site-packages'

  apt:
    arch: amd64
    sources:
      - sourceline: 'deb http://archive.ubuntu.com/ubuntu/ jammy main restricted'
        key_url: 'http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xf6ecb3762474eda9d21b7022871920d1991bc93c'
    include:
      - python3
    exclude: []

  files:
    include:
      - '/usr/bin/env'

  test:
    fedora-30:
      image: appimagecrafters/tests-env:fedora-33
      command: ./AppRun --latitude=50.5824 --longitude=3.0624
      use_host_x: true
    debian-stable:
      image: appimagecrafters/tests-env:debian-stable
      command: ./AppRun --latitude=50.5824 --longitude=3.0624
      use_host_x: true
    archlinux-latest:
      image: appimagecrafters/tests-env:archlinux-latest
      command: ./AppRun --latitude=50.5824 --longitude=3.0624
      use_host_x: true
    centos-7:
      image: appimagecrafters/tests-env:centos-7
      command: ./AppRun --latitude=50.5824 --longitude=3.0624
      use_host_x: true
    ubuntu-xenial:
      image: appimagecrafters/tests-env:ubuntu-xenial
      command: ./AppRun --latitude=50.5824 --longitude=3.0624
      use_host_x: true

AppImage:
  arch: x86_64
  update-information: gh-releases-zsync|Kosmorro|kosmorro|latest|Kosmorro-*x86_64.AppImage.zsync
```

What am I missing?
