### ISSUE TITLE
Host configuration leaks into gdk-pixbuf loaders.conf file

### ISSUE THREAD

**Issue by goldstar611** [AppImageCrafters/appimage-builder#277]
I have a [gtk2.0 app](https://github.com/goldstar611/chirp-appimage) that I am trying to debug an issue where gdk-pixbuf loader support for png and jpeg files are missing in my app. This manifests itself as missing icons in the app.

I used auditd to track which process is creating the loaders.cache file and it appears to be appimagebuilder.

Here is what I know:
- My AppImage is created from Ubuntu Bionic (18.04) and Xenial (16.04) apt sources
- Container OS is running Ubuntu Jammy (22.04)
- `AppDir/usr/lib/i386-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache` has this comment `Created by gdk-pixbuf-query-loaders from gdk-pixbuf-2.42.8`
- `gdk-pixbuf` version 2.42.8 is not available until Ubuntu Jammy, so some host OS information is leaking INTO the AppImage
- The container OS does not include loaders for png or jpeg
- My AppImage has shared libraries for png and jpeg but loaders.conf does not include them

My theory is that AppImage Builder is using the host `gdk-pixbuf-query-loaders` utility and that binary is searching the available host loaders and writing that file into my AppImage instead of searching the available loaders from AppDir.

P.S. Is there a way to get the "arch triplet" during build time? i.e. "i386-linux-gnu"

I'll work on a minimal test case.

[Edit] Copying my own loaders.cache file as a `after_bundle` step doesn't work because the loaders.cache file is updated after the `after_bundle` step. So this is a blocker for my app

**Comment by goldstar611** [comment]
Reproduction script, please run `appimagebuilder` on Ubuntu 22.04 OS

```yaml
version: 1

script:
  - rm -rf AppDir  | true

AppDir:
  path: ./AppDir
  
  app_info:
    id: com.github.appimage-builder
    name: issue-277
    icon: utilities-terminal
    version: "1"
    exec: bin/bash

  apt:
    arch: amd64
    sources:
      - sourceline: deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ bionic main
        key_url: http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3b4fe6acc0b21f32

    include:
      - bash
      - gnome-themes-extra

AppImage:
  sign-key: None
  arch: x86_64
```

You should see the following files (plus others)
-  `./AppDir/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache`
- `./AppDir/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-png.so`
- `./AppDir/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-jpeg.so`

Inside `./AppDir/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache` you will see that there is no reference to `libpixbufloader-png.so` or `libpixbufloader-jpeg.so`
