### ISSUE TITLE
aarch64 builds made from debian repository are not working.

### ISSUE THREAD

**Issue by JohnXLivingston** [AppImageCrafters/appimage-builder#278]
I have issues to make aarch64 AppImage based on Debian repository, build from an x86_64 machine.
I have errors like `APPRUN_ERROR: No such file or directory`, but the file missing file/directory is not shown.
And when I run strace, the execute ends with a `execve` on the exec script, and it fails although the file exists.

Note: the same build for x86_64 works fine.

So, I decided to test with an official example.
I copied this one: https://appimage-builder.readthedocs.io/en/latest/examples/bash.html
Well, it is working fine!

Then, I just replaced the ubuntu repository by the debian ones.
And I got the same error as in my project !

Here is the yml file:

```yaml
version: 1

AppDir:
  path: ./AppDir

  app_info:
    id: org.gnu.bash
    name: bash
    icon: utilities-terminal
    version: 4.4.20
    exec: bin/bash
    exec_args: $@

  apt:
    arch: arm64
    sources:
      # - sourceline: 'deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports bionic main'
      #   key_url: 'http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3b4fe6acc0b21f32'
      - sourceline: 'deb [arch=arm64] https://deb.debian.org/debian/ bullseye main contrib'
        key_url: 'http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x648ACFD622F3D138'

    include:
      - bash
      - coreutils
    exclude:
      - libpcre3


AppImage:
  arch: aarch64
```

And the error when running on a ARM64:

```bash
$ ./bash-4.4.20-aarch64.AppImage 
APPRUN_ERROR: No such file or director
```

appimage-builder version: 1.1.0

PS: Thanks for your work, appimage-builder helped me a lot in my project!
