### ISSUE TITLE
Getting `UnicodeDecodeError` when building

### ISSUE THREAD

**Issue by hwittenborn** [AppImageCrafters/appimage-builder#284]
I'm not sure why, but whenever I run a build I get an error message saying `UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 574750: invalid continuation byte`. I've tested it with the following example:

```yml
version: 1

AppDir:
  path: ./AppDir

  app_info:
    id: com.example.testing
    name: Testing
    icon: firefox
    version: 0.1.0
    exec: usr/bin/echo
    exec_args: "$@"
  
  apt:
    arch: amd64
    sources:
      - sourceline: 'deb http://us.archive.ubuntu.com/ubuntu/ kinetic main'
        key_url: 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xf6ecb3762474eda9d21b7022871920d1991bc93c'
    include:
      - bash
  
AppImage:
  update-information: None
  sign-key: None
  arch: x86_64
```

I'm on Ubuntu 22.10 for my build system. Sorry I can't send a full traceback, there's a lot of personal information in it that I don't want to send over much.
