### ISSUE TITLE
APPRUN_ERROR: No such file or directory due to broken symlink

### ISSUE THREAD

**Issue by alberic89** [AppImageCrafters/appimage-builder#304]
My AppImage (see the recipe in attachment) is executable only on the build machine.
If I try to run on other OS or machine, I got the error `APPRUN_ERROR: No such file or directory`.
In the AppRun.env file, the last line is `APPDIR_LIBC_LINKER_PATH={'lib/ld-linux-aarch64.so.1'}`
It's refer to a symlink who points to `aarch64-linux-gnu/ld-2.31.so`, a broken symlink who points to `ld-2.31.so`, but the right of location of `ld-2.31.so` is `runtime/compact/lib/aarch64-linux-gnu/ld-2.31.so`.
How to fix this ?

OS : Raspberry Pi OS
architecture : arm64 (aarch64)
appimage-builder version : latest pip standard installation
[AppImageBuilder.yml.txt](https://github.com/AppImageCrafters/appimage-builder/files/11099389/AppImageBuilder.yml.txt)
[AppRun.env.txt](https://github.com/AppImageCrafters/appimage-builder/files/11099394/AppRun.env.txt)

**Comment by damoclark** [comment]
hi @perrito666 

I am experiencing the same error as @alberic89 except that I see no broken symlinks as @alberic89  describes in my aarch64 build.  On checking all the path variables and files located in those paths, I am not finding any broken links.  

I also have an identical build for the x86_64 architecture that works perfectly fine.  All I did was compile the source code on an arm64 computer (Raspberry Pi 5B), and copied it over to the x86_64 machine I am using.  Then I updated yaml file so the apt platform uses an arm64 repository, and then and built the image copying the compiled source code into the AppDir, just as I did for the x86 code.  The arm appimage builds no problem.

However, when I execute it on the arm computer, I get `APPRUN_ERROR: No such file or directory`.

I noted the debian bookworm apt repositories used on the arm machine where I compiled the source, and used the exact same apt repositories under the `apt` section of the yaml file.  So the appimage build uses the same repo packages to build the image as was used to compile the software.

I can run the compiled arm code natively on the arm machine okay.  

I've cross-checked the files between the two images by extracting them both to see what differences there are.  I've attached a path diff (at very bottom) so you can see how the x86 and arm squashfs images compare.  I noticed that the `ld-linux-aarch64.so.1` and the `ld-linux-x86-64.so.2` are located in different paths between the two appimages.  I wonder whether this might be the cause.

### environments
aarch64 OS: Raspberry Pi OS (Debian Bookworm 12.4)
x86_64 OS: Ubuntu 22.04
appimage-builder: appimage-builder-1.1.1.dev32+g2709a3b-x86_64.AppImage

### commands used

```bash
FLOM_INSTALL_PREFIX_DIR=/tmp/flom FLOM_VERSION=1.7.1 appimage-builder-1.1.1.dev32+g2709a3b-x86_64.AppImage --recipe <recipe filename>
```

### x86 yaml
```yaml
# Command to build an appimage for flom 1.7.1
# cd flom-1.7.1
# make clean
# ./configure --prefix=/tmp/flom --disable-{php,perl,python,java}
# make -j2
# make install
#
# FLOM_INSTALL_PREFIX_DIR=/tmp/flom FLOM_VERSION=1.7.1 appimage-builder-1.1.1.dev32+g2709a3b-x86_64.AppImage --recipe flom-aarch64.yml
#
version: 1
script:
  # Remove any previous build
  - rm -rf AppDir  || true
  # Make usr dir
  - "mkdir -p AppDir/usr"
  # Copy the install location for flom into appdir with everything under usr
  - 'tar cvf - -C "{{FLOM_INSTALL_PREFIX_DIR}}" . | tar xf - -C AppDir/usr/'
 
AppDir:
  path: ./AppDir

  app_info:
    id: org.tiian.flom
    name: flom
    icon: utilities-terminal
    version: "{{FLOM_VERSION}}"
    # Set the executable as entry point
    exec: usr/bin/flom

  apt:
    arch: "amd64"
    sources:
      - sourceline: 'deb http://archive.ubuntu.com/ubuntu/ jammy main restricted universe multiverse'
        key_url: 'http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x871920D1991BC93C'

    include:
      - fuse3 # So flom can mount its state fuse filesystem
      - openssl # For encryption between client/server
      - dbus # Not sure what this is used for
    exclude: []

  files:
    exclude: 
      - "usr/share/*"
      - "usr/include/*"
      
  runtime:
    path_mappings:
      # The compiled default for flom.conf is remapped to somewhere sensible
      - "{{FLOM_INSTALL_PREFIX_DIR}}/etc/flom.conf:/usr/local/etc/flom.conf"

  test:
    fedora:
      image: appimagecrafters/tests-env:fedora-30
      command: ./AppRun
      use_host_x: true
    debian:
      image: appimagecrafters/tests-env:debian-stable
      command: ./AppRun
      use_host_x: true
    arch:
      image: appimagecrafters/tests-env:archlinux-latest
      command: ./AppRun
      use_host_x: true
    centos:
      image: appimagecrafters/tests-env:centos-7
      command: ./AppRun
      use_host_x: true
    ubuntu:
      image: appimagecrafters/tests-env:ubuntu-xenial
      command: ./AppRun
      use_host_x: true

AppImage:
  # Dont know what this means yet - need to figure it out
  update-information: guess
  sign-key: None
  arch: "x86_64"
```

### arm yaml
```yaml
# Error:
# APPRUN_ERROR: No such file or directory
# https://github.com/AppImageCrafters/appimage-builder/issues/304
#
# Command to build an appimage for flom 1.7.1
# cd flom-1.7.1
# make clean
# ./configure --prefix=/tmp/flom --disable-{php,perl,python,java}
# make -j2
# make install
#
# FLOM_INSTALL_PREFIX_DIR=/tmp/flom FLOM_VERSION=1.7.1 appimage-builder-1.1.1.dev32+g2709a3b-x86_64.AppImage --recipe flom-aarch64.yml
#
version: 1
script:
  # Remove any previous build
  - rm -rf AppDir  || true
  # Make usr dir
  - "mkdir -p AppDir/usr"
  # Copy the install location for flom into appdir with everything under usr
  - 'tar cvf - -C "{{FLOM_INSTALL_PREFIX_DIR}}" . | tar xf - -C AppDir/usr/'
 
AppDir:
  path: ./AppDir

  app_info:
    id: org.tiian.flom
    name: flom
    icon: utilities-terminal
    version: "{{FLOM_VERSION}}"
    # Set the executable as entry point
    exec: usr/bin/flom

  apt:
    arch: "arm64"
    sources:
      # arm sources and key_url from
      # https://ftp-master.debian.org/keys.html
      - sourceline: 'deb http://deb.debian.org/debian bookworm main contrib non-free non-free-firmware'
        key_url: 'https://ftp-master.debian.org/keys/archive-key-12.asc'
      - sourceline: 'deb http://deb.debian.org/debian-security/ bookworm-security main contrib non-free non-free-firmware'
        key_url: 'https://ftp-master.debian.org/keys/archive-key-12-security.asc'
      - sourceline: 'deb http://deb.debian.org/debian bookworm-updates main contrib non-free non-free-firmware'
        key_url: 'https://ftp-master.debian.org/keys/release-12.asc'
      - sourceline: 'deb http://archive.raspberrypi.com/debian/ bookworm main'
        key_url: 'http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x82B129927FA3303E'

    include:
      - fuse3 # So flom can mount its state fuse filesystem
      - openssl # For encryption between client/server
      - dbus # Not sure what this is used for
    exclude: []

  files:
    exclude: 
      - "usr/share/*"
      - "usr/include/*"
      
  runtime:
    path_mappings:
      # The compiled default for flom.conf is remapped to somewhere sensible
      - "{{FLOM_INSTALL_PREFIX_DIR}}/etc/flom.conf:/usr/local/etc/flom.conf"

  test:
    fedora:
      image: appimagecrafters/tests-env:fedora-30
      command: ./AppRun
      use_host_x: true
    debian:
      image: appimagecrafters/tests-env:debian-stable
      command: ./AppRun
      use_host_x: true
    arch:
      image: appimagecrafters/tests-env:archlinux-latest
      command: ./AppRun
      use_host_x: true
    centos:
      image: appimagecrafters/tests-env:centos-7
      command: ./AppRun
      use_host_x: true
    ubuntu:
      image: appimagecrafters/tests-env:ubuntu-xenial
      command: ./AppRun
      use_host_x: true

AppImage:
  # Dont know what this means yet - need to figure it out
  update-information: guess
  sign-key: None
  arch: "aarch64"
```


### path diff
[appimage-diff.html.zip](https://github.com/AppImageCrafters/appimage-builder/files/14081037/appimage-diff.html.zip)
