### ISSUE TITLE
ERROR:root:"apt-get update" execution failed

### ISSUE THREAD

**Issue by konceptosociala** [AppImageCrafters/appimage-builder#305]
System: Ubuntu 20.04

```
sudo appimage-builder --recipe AppImageBuilder.yml --skip-test
```

```
INFO:main:Running main script
INFO:main:Running apt deploy
INFO:apt:apt-get update
Get:1 http://ua.archive.ubuntu.com/ubuntu focal InRelease [265 kB]
Ign:2 http://ppa.launchpad.net/thomas-schiex/blender-legacy/ubuntu focal InRelease                                                                      
Get:3 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]                                                                               
Get:4 https://dl.google.com/linux/chrome/deb stable InRelease [1811 B]                                       
Get:5 http://ppa.launchpad.net/keymanapp/keyman/ubuntu focal InRelease [24,3 kB]                                          
Get:6 http://ua.archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]                           
Ign:4 https://dl.google.com/linux/chrome/deb stable InRelease                                       
Ign:1 http://ua.archive.ubuntu.com/ubuntu focal InRelease                                             
Get:7 http://ua.archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]                                           
Ign:5 http://ppa.launchpad.net/keymanapp/keyman/ubuntu focal InRelease                  
Get:8 http://ppa.launchpad.net/papirus/papirus/ubuntu focal InRelease [18,0 kB]           
Ign:6 http://ua.archive.ubuntu.com/ubuntu focal-updates InRelease                                    
Ign:7 http://ua.archive.ubuntu.com/ubuntu focal-backports InRelease                                    
Get:9 http://ppa.launchpad.net/ondrej/php/ubuntu focal InRelease [23,9 kB]
Ign:3 http://security.ubuntu.com/ubuntu focal-security InRelease
Get:10 http://ppa.launchpad.net/atareao/lplayer/ubuntu focal InRelease [17,5 kB]
Ign:8 http://ppa.launchpad.net/papirus/papirus/ubuntu focal InRelease
Ign:9 http://ppa.launchpad.net/ondrej/php/ubuntu focal InRelease
Get:11 http://ppa.launchpad.net/frinksy/airshipper/ubuntu focal InRelease [18,1 kB]
Ign:10 http://ppa.launchpad.net/atareao/lplayer/ubuntu focal InRelease
Get:12 http://ppa.launchpad.net/makehuman-official/makehuman-community/ubuntu focal InRelease [18,1 kB]
Ign:11 http://ppa.launchpad.net/frinksy/airshipper/ubuntu focal InRelease
Ign:13 http://ppa.launchpad.net/thomas-schiex/blender-legacy/ubuntu focal Release
Ign:12 http://ppa.launchpad.net/makehuman-official/makehuman-community/ubuntu focal InRelease
Ign:14 http://ppa.launchpad.net/thomas-schiex/blender-legacy/ubuntu focal/main all Packages
Ign:15 http://ppa.launchpad.net/thomas-schiex/blender-legacy/ubuntu focal/main amd64 Packages
Ign:14 http://ppa.launchpad.net/thomas-schiex/blender-legacy/ubuntu focal/main all Packages
Ign:15 http://ppa.launchpad.net/thomas-schiex/blender-legacy/ubuntu focal/main amd64 Packages
Ign:14 http://ppa.launchpad.net/thomas-schiex/blender-legacy/ubuntu focal/main all Packages
Ign:15 http://ppa.launchpad.net/thomas-schiex/blender-legacy/ubuntu focal/main amd64 Packages
Ign:14 http://ppa.launchpad.net/thomas-schiex/blender-legacy/ubuntu focal/main all Packages
Ign:15 http://ppa.launchpad.net/thomas-schiex/blender-legacy/ubuntu focal/main amd64 Packages
Ign:14 http://ppa.launchpad.net/thomas-schiex/blender-legacy/ubuntu focal/main all Packages
Ign:15 http://ppa.launchpad.net/thomas-schiex/blender-legacy/ubuntu focal/main amd64 Packages
Ign:14 http://ppa.launchpad.net/thomas-schiex/blender-legacy/ubuntu focal/main all Packages
Ign:15 http://ppa.launchpad.net/thomas-schiex/blender-legacy/ubuntu focal/main amd64 Packages
Ign:14 http://ppa.launchpad.net/thomas-schiex/blender-legacy/ubuntu focal/main all Packages
Err:15 http://ppa.launchpad.net/thomas-schiex/blender-legacy/ubuntu focal/main amd64 Packages
  404  Not Found [IP: 185.125.190.52 80]
Fetched 723 kB in 6s (113 kB/s)
Reading package lists... Done
W: GPG error: https://dl.google.com/linux/chrome/deb stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 4EB27DB2A3B88B8B
W: The repository 'https://dl.google.com/linux/chrome/deb stable InRelease' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://ua.archive.ubuntu.com/ubuntu focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 3B4FE6ACC0B21F32 NO_PUBKEY 871920D1991BC93C
W: The repository 'http://ua.archive.ubuntu.com/ubuntu focal InRelease' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://ppa.launchpad.net/keymanapp/keyman/ubuntu focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B033BBD612B4B657
W: The repository 'http://ppa.launchpad.net/keymanapp/keyman/ubuntu focal InRelease' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://ua.archive.ubuntu.com/ubuntu focal-updates InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 3B4FE6ACC0B21F32 NO_PUBKEY 871920D1991BC93C
W: The repository 'http://ua.archive.ubuntu.com/ubuntu focal-updates InRelease' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://ua.archive.ubuntu.com/ubuntu focal-backports InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 3B4FE6ACC0B21F32 NO_PUBKEY 871920D1991BC93C
W: The repository 'http://ua.archive.ubuntu.com/ubuntu focal-backports InRelease' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://security.ubuntu.com/ubuntu focal-security InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 3B4FE6ACC0B21F32 NO_PUBKEY 871920D1991BC93C
W: The repository 'http://security.ubuntu.com/ubuntu focal-security InRelease' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://ppa.launchpad.net/papirus/papirus/ubuntu focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY E58A9D36647CAE7F
W: The repository 'http://ppa.launchpad.net/papirus/papirus/ubuntu focal InRelease' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://ppa.launchpad.net/ondrej/php/ubuntu focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 4F4EA0AAE5267A6C
W: The repository 'http://ppa.launchpad.net/ondrej/php/ubuntu focal InRelease' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://ppa.launchpad.net/atareao/lplayer/ubuntu focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6A9653F936FD5529
W: The repository 'http://ppa.launchpad.net/atareao/lplayer/ubuntu focal InRelease' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://ppa.launchpad.net/frinksy/airshipper/ubuntu focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 33EB7559057A22D2
W: The repository 'http://ppa.launchpad.net/frinksy/airshipper/ubuntu focal InRelease' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: The repository 'http://ppa.launchpad.net/thomas-schiex/blender-legacy/ubuntu focal Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://ppa.launchpad.net/makehuman-official/makehuman-community/ubuntu focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 4303741FD4B25E55
W: The repository 'http://ppa.launchpad.net/makehuman-official/makehuman-community/ubuntu focal InRelease' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://ppa.launchpad.net/thomas-schiex/blender-legacy/ubuntu/dists/focal/main/binary-amd64/Packages  404  Not Found [IP: 185.125.190.52 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.
ERROR:root:"apt-get update" execution failed
Traceback (most recent call last):
  File "/tmp/.mount_appimaQrBj4K//usr/bin/appimage-builder", line 8, in <module>
    sys.exit(__main__())
  File "/tmp/.mount_appimaQrBj4K/usr/lib/python3.8/site-packages/appimagebuilder/__main__.py", line 44, in __main__
    invoker.execute(commands)
  File "/tmp/.mount_appimaQrBj4K/usr/lib/python3.8/site-packages/appimagebuilder/invoker.py", line 29, in execute
    command()
  File "/tmp/.mount_appimaQrBj4K/usr/lib/python3.8/site-packages/appimagebuilder/commands/apt_deploy.py", line 46, in __call__
    deployed_packages = apt_deploy.deploy(
  File "/tmp/.mount_appimaQrBj4K/usr/lib/python3.8/site-packages/appimagebuilder/modules/deploy/apt/deploy.py", line 40, in deploy
    self._prepare_apt_venv()
  File "/tmp/.mount_appimaQrBj4K/usr/lib/python3.8/site-packages/appimagebuilder/modules/deploy/apt/deploy.py", line 49, in _prepare_apt_venv
    self.apt_venv.update()
  File "/tmp/.mount_appimaQrBj4K/usr/lib/python3.8/site-packages/appimagebuilder/modules/deploy/apt/venv.py", line 160, in update
    shell.assert_successful_result(_proc)
  File "/tmp/.mount_appimaQrBj4K/usr/lib/python3.8/site-packages/appimagebuilder/utils/shell.py", line 33, in assert_successful_result
    raise RuntimeError(
RuntimeError: "apt-get update" execution failed with code 100
```

I can't find any information about such issue

**Comment by MCUmbrella** [comment]
same problem. now i cant even build the example appimage in the tutorial

console output:
```
~/qt-appimage-template$ appimage-builder 
INFO:main:Running main script
INFO:main:Running apt deploy
INFO:apt:apt-get update
获取:1 http://old-releases.ubuntu.com/ubuntu impish InRelease [270 kB]
忽略:1 http://old-releases.ubuntu.com/ubuntu impish InRelease
获取:2 http://old-releases.ubuntu.com/ubuntu impish-security InRelease [110 kB]
忽略:2 http://old-releases.ubuntu.com/ubuntu impish-security InRelease
获取:3 http://old-releases.ubuntu.com/ubuntu impish/main amd64 Packages [1,396 kB]
获取:4 http://old-releases.ubuntu.com/ubuntu impish/universe amd64 Packages [13.1 MB]
获取:5 http://old-releases.ubuntu.com/ubuntu impish/multiverse amd64 Packages [209 kB]                                                                                                                                                      
获取:6 http://old-releases.ubuntu.com/ubuntu impish-security/universe amd64 Packages [207 kB]                                                                                                                                               
获取:7 http://old-releases.ubuntu.com/ubuntu impish-security/main amd64 Packages [238 kB]                                                                                                                                                   
获取:8 http://old-releases.ubuntu.com/ubuntu impish-security/multiverse amd64 Packages [4,776 B]                                                                                                                                            
已下载 15.5 MB，耗时 17秒 (906 kB/s)                                                                                                                                                                                                        
正在读取软件包列表... 完成
W: GPG 错误：http://old-releases.ubuntu.com/ubuntu impish InRelease: 由于没有公钥，无法验证下列签名： NO_PUBKEY 871920D1991BC93C
W: GPG 错误：http://old-releases.ubuntu.com/ubuntu impish-security InRelease: 由于没有公钥，无法验证下列签名： NO_PUBKEY 871920D1991BC93C
Traceback (most recent call last):
  File "/usr/local/bin/appimage-builder", line 8, in <module>
    sys.exit(__main__())
  File "/usr/local/lib/python3.9/dist-packages/appimagebuilder/__main__.py", line 50, in __main__
    invoker.execute(commands)
  File "/usr/local/lib/python3.9/dist-packages/appimagebuilder/invoker.py", line 29, in execute
    command()
  File "/usr/local/lib/python3.9/dist-packages/appimagebuilder/commands/apt_deploy.py", line 46, in __call__
    deployed_packages = apt_deploy.deploy(
  File "/usr/local/lib/python3.9/dist-packages/appimagebuilder/modules/deploy/apt/deploy.py", line 39, in deploy
    self._prepare_apt_venv()
  File "/usr/local/lib/python3.9/dist-packages/appimagebuilder/modules/deploy/apt/deploy.py", line 55, in _prepare_apt_venv
    apt_core_packages = self._remove_old_packages(apt_core_packages)
  File "/usr/local/lib/python3.9/dist-packages/appimagebuilder/modules/deploy/apt/deploy.py", line 93, in _remove_old_packages
    if package > latest_packages[pkg_tuple]:
  File "/usr/local/lib/python3.9/dist-packages/appimagebuilder/modules/deploy/apt/package.py", line 79, in __gt__
    return version.parse(self.version) > version.parse(other.version)
  File "/home/mcumbrella/.local/lib/python3.9/site-packages/packaging/version.py", line 54, in parse
    return Version(version)
  File "/home/mcumbrella/.local/lib/python3.9/site-packages/packaging/version.py", line 200, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: '1.20.9ubuntu2'
```

AppImageBuilder.yml:
```yaml
# appimage-builder recipe see https://appimage-builder.readthedocs.io for details
version: 1
AppDir:
  path: /home/mcumbrella/qt-appimage-template/AppDir
  app_info:
    id: QtQuickControls2Application
    name: SimpleQtApp
    icon: QtQuickControls2Application
    version: latest
    exec: usr/bin/qt-appimage-template
    exec_args: $@
  apt:
    arch:
    - amd64
    allow_unauthenticated: true
    sources:
    - sourceline: deb [trusted=yes] http://old-releases.ubuntu.com/ubuntu impish main
    - sourceline: deb [trusted=yes] http://old-releases.ubuntu.com/ubuntu impish universe
    - sourceline: deb [trusted=yes] http://old-releases.ubuntu.com/ubuntu impish multiverse
    - sourceline: deb [trusted=yes] http://old-releases.ubuntu.com/ubuntu impish-security main
    - sourceline: deb [trusted=yes] http://old-releases.ubuntu.com/ubuntu impish-security universe
    - sourceline: deb [trusted=yes] http://old-releases.ubuntu.com/ubuntu impish-security multiverse
    include:
    - breeze-icon-theme
    - fcitx-frontend-qt5:amd64
    - hwdata
    - kubuntu-settings-desktop
    - language-pack-zh-hans-base
    - libbz2-1.0:amd64
    - libcap2:amd64
    - libgamin0
    - libgcrypt20:amd64
    - libkf5iconthemes-bin
    - liblz4-1:amd64
    - libnvidia-common-515
    - libnvidia-gl-515:amd64
    - libpcre3:amd64
    - libsm6:amd64
    - libsystemd0:amd64
    - libxcb-render-util0:amd64
    - libxcb-sync1:amd64
    - libxcb-xinerama0:amd64
    - libxcb-xkb1:amd64
    - libxdmcp6:amd64
    - libxext6:amd64
    - libxfixes3:amd64
    - libxrender1:amd64
    - plasma-integration
    - plasma-workspace-data
    - qml-module-qtquick-controls2:amd64
    - qml-module-qtquick-layouts:amd64
    - qml-module-qtquick-templates2:amd64
    - qml-module-qtquick-window2:amd64
    - qml-module-qtquick2:amd64
    - qt5-gtk-platformtheme:amd64
    - qttranslations5-l10n
    - qtvirtualkeyboard-plugin:amd64
    - qtwayland5:amd64
    - tzdata
  files:
    include:
    - /home/mcumbrella/.icons/KDE-classic/cursors/ibeam
    - /home/mcumbrella/.icons/KDE-classic/cursors/left_ptr
    - /home/mcumbrella/.local/share/icons/Memphis98/index.theme
    - /lib/x86_64-linux-gnu/libGLX_nvidia.so.0
    - /lib/x86_64-linux-gnu/libKF5KIOFileWidgets.so.5
    - /lib/x86_64-linux-gnu/libKF5Notifications.so.5
    - /lib/x86_64-linux-gnu/libKF5WaylandClient.so.5
    - /lib/x86_64-linux-gnu/libQt5QmlWorkerScript.so.5
    - /lib/x86_64-linux-gnu/libQt5QuickControls2.so.5
    - /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
    - /lib/x86_64-linux-gnu/libXcursor.so.1
    - /usr/lib/locale/locale-archive
    - /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
    - /usr/lib/x86_64-linux-gnu/libbz2.so.1.0.4
    - /usr/lib/x86_64-linux-gnu/libc.so.6
    - /usr/lib/x86_64-linux-gnu/libcap.so.2.44
    - /usr/lib/x86_64-linux-gnu/libcom_err.so.2.1
    - /usr/lib/x86_64-linux-gnu/libdbus-1.so.3.19.13
    - /usr/lib/x86_64-linux-gnu/libdl.so.2
    - /usr/lib/x86_64-linux-gnu/libexpat.so.1.8.1
    - /usr/lib/x86_64-linux-gnu/libgcc_s.so.1
    - /usr/lib/x86_64-linux-gnu/libgpg-error.so.0.29.0
    - /usr/lib/x86_64-linux-gnu/libkeyutils.so.1.9
    - /usr/lib/x86_64-linux-gnu/liblzma.so.5.2.5
    - /usr/lib/x86_64-linux-gnu/libm.so.6
    - /usr/lib/x86_64-linux-gnu/libpcre.so.3.13.3
    - /usr/lib/x86_64-linux-gnu/libpthread.so.0
    - /usr/lib/x86_64-linux-gnu/libresolv.so.2
    - /usr/lib/x86_64-linux-gnu/librt.so.1
    - /usr/lib/x86_64-linux-gnu/libselinux.so.1
    - /usr/lib/x86_64-linux-gnu/libz.so.1.2.11
    - /usr/local/share/fonts/l/Lyusung_210618.ttf
    exclude:
    - usr/share/man
    - usr/share/doc/*/README.*
    - usr/share/doc/*/changelog.*
    - usr/share/doc/*/NEWS.*
    - usr/share/doc/*/TODO.*
  test:
    fedora-30:
      image: appimagecrafters/tests-env:fedora-30
      command: ./AppRun
    debian-stable:
      image: appimagecrafters/tests-env:debian-stable
      command: ./AppRun
    archlinux-latest:
      image: appimagecrafters/tests-env:archlinux-latest
      command: ./AppRun
    centos-7:
      image: appimagecrafters/tests-env:centos-7
      command: ./AppRun
    ubuntu-xenial:
      image: appimagecrafters/tests-env:ubuntu-xenial
      command: ./AppRun
AppImage:
  arch: x86_64
  update-information: guess
```
