### ISSUE TITLE
Allow to dynamically set application version

### ISSUE THREAD

**Issue by trollixx** [AppImageCrafters/appimage-builder#40]
Currently app/appimage version needs to be hard-coded in the manifest like this:

```yaml
AppDir:
  path: build.appimage/AppDir

  app_info:
    id: org.zealdocs.Zeal
    name: zeal
    icon: zeal
    version: 0.6.1 #  <-- hard-coded version
    exec: usr/bin/zeal
    exec_args: $@
```

I am trying to create a pipeline for producing AppImage packages for each CI build. In this scenario version is not known upfront but rather is calculated by `git describe`. It would be great if there was an option to read the version value from the environment so it could be set in the `script` section.

**Comment by azubieta** [comment]
You can use environment variables in the yml file like this:
```yaml
AppDir:
  app_info:
    version: !ENV ${APP_VERSION}
```
More details about how to use environment variables in the link below:
https://appimage-builder.readthedocs.io/en/latest/reference/version_1.html#environment-variables

**Comment by trollixx** [comment]
Hm, I think I tried `${VAR_NAME}` and that didn't work. Maybe because I was trying to export in the `script` block.

**Comment by lulol** [comment]
Is this feature still working?

Only the static definitions seems to work inside the recipe.

Although can define the version dynamically adding the variables to the environment with `export VAR=VALUE` before calling appimage-builder and using `${VAR}` in the recipe, this is not as convenient.

```
# appimage-builder recipe see https://appimage-builder.readthedocs.io for details
version: 1

script:
  - rm -rf AppDir
  - echo "APP_VERSION=1.2.3" >> $BUILDER_ENV
  - export APP_VERSION=1.2.3 # https://azubieta.net/p/exporting-environment-variables-on-appimage-builder/

AppDir:
  path: ./AppDir

  app_info:
    id: test
    name: test
#    name: test {{BUILDER_ENV}} # https://azubieta.net/p/exporting-environment-variables-on-appimage-builder/
    icon: test
#    version: !ENV ${APP_VERSION} # https://github.com/AppImageCrafters/appimage-builder/issues/40#issuecomment-687842631
#    version: '{{APP_VERSION}}' # https://azubieta.net/p/exporting-environment-variables-on-appimage-builder/
    version: {{APP_VERSION}} # https://appimage-builder.readthedocs.io/en/latest/reference/recipe.html#environment-variables
#    version: ${APP_VERSION}
#    version: 1.1.1
    exec: test
    exec_args: $@
```
