### ISSUE TITLE
Improve recipe

### ISSUE THREAD

**Issue by azubieta** [AppImageCrafters/appimage-builder#45]
```yml
---
version: 2

AppDir:
  id: org.kde.kcalc
  name: kcalc
  icon: accessories-calculator
  version: 17.12.3

  path: ./AppDir

  recipe:
    - name: "Deploy application binaries"
      uses: bash
      script:
        - mkdir -p ${{ AppDir.path }}

    - name: "Deploy dependencies using apt"
      uses: apt
      settings:
        sources:
          - 'deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ bionic main restricted universe multiverse'
        keys:
          - 'http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3b4fe6acc0b21f32'
      install:
        - kcalc
        - libpulse0
      exclude:
        - phonon4qt5
        - libkf5service-bin
        - perl
        - perl-base
        - libpam-runtime

    - name: 'Deploy runtime'
      uses: apprun-deploy
      exec: bin/ls
      exec_args: $@

      runtime_environment:
        APPDIR_LIBRARY_PATH: '$APPDIR/lib:$APPDIR:/usr/lib'

      path_mappings:
        - /usr/share/app:$APPDIR:/usr/share/app

    - name: 'Lint'
      uses: appdir-lint

  tests:
    - name: debian
      runner: docker
      image: ubuntu
      before_script:
        - mkdir -p $HOME
      script: ./AppRun

AppImage:
  arch: x86_64
  update_information: None
  sign_key: None
  sign_key_passprace: None



```
