### ISSUE TITLE
Build started failing with "Could not perform immediate configuration on"

### ISSUE THREAD

**Issue by grimmy** [AppImageCrafters/appimage-builder#54]
As far as I know nothing changed on my side, but I do my builds in a docker container that is updated weekly so it may have pulled a new version of appimagebuilder.  To test that theory I rebuilt the build container with release 12 and got the same result.  The log of the build is below.  If you want/need full build instructions or just an app image to start with, let me know and I can make that available.

>  INFO:root:=================
INFO:root:Generating AppDir
INFO:root:=================
INFO:root:
INFO:root:Bundling dependencies
INFO:root:---------------------
INFO:root:Importing key: https://ftp-master.debian.org/keys/archive-key-10.asc
INFO:apt-key:fakeroot apt-key --keyring ./appimage-builder-cache/etc/apt/trusted.gpg add -
INFO:apt-get:/usr/bin/apt-get -c ./appimage-builder-cache/etc/apt/apt.conf update
INFO:apt-get:Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]
INFO:apt-get:Get:2 http://deb.debian.org/debian bullseye/main amd64 Packages [7,806 kB]
INFO:apt-get:Get:3 http://deb.debian.org/debian bullseye/main Translation-en [5,969 kB]
INFO:apt-get:Fetched 13.9 MB in 3s (4,673 kB/s)
INFO:apt-get:Reading package lists...
INFO:apt-get:/usr/bin/apt-get -c ./appimage-builder-cache/etc/apt/apt.conf --download-only -y --no-install-recommends --simulate install libc6 zlib1g libstdc++6
WARNING:apt-get:E: Could not configure 'libc6:amd64'.
WARNING:apt-get:E: Could not perform immediate configuration on 'libgcc-s1:amd64'. Please see man 5 apt.conf under APT::Immediate-Configure for details. (2)
WARNING:apt-get:E: Could not configure 'libc6:amd64'.
WARNING:apt-get:E: Could not perform immediate configuration on 'libcom-err2:amd64'. Please see man 5 apt.conf under APT::Immediate-Configure for details. (2)
WARNING:apt-get:E: Could not configure 'libc6:amd64'.
WARNING:apt-get:E: Could not perform immediate configuration on 'libkrb5support0:amd64'. Please see man 5 apt.conf under APT::Immediate-Configure for details. (2)
WARNING:apt-get:E: Could not configure 'libc6:amd64'.
WARNING:apt-get:E: Could not perform immediate configuration on 'libk5crypto3:amd64'. Please see man 5 apt.conf under APT::Immediate-Configure for details. (2)
WARNING:apt-get:E: Could not configure 'libc6:amd64'.
WARNING:apt-get:E: Could not perform immediate configuration on 'libkeyutils1:amd64'. Please see man 5 apt.conf under APT::Immediate-Configure for details. (2)
WARNING:apt-get:E: Could not configure 'libc6:amd64'.
WARNING:apt-get:E: Could not perform immediate configuration on 'libssl1.1:amd64'. Please see man 5 apt.conf under APT::Immediate-Configure for details. (2)
WARNING:apt-get:E: Could not configure 'libc6:amd64'.
WARNING:apt-get:E: Could not perform immediate configuration on 'libkrb5-3:amd64'. Please see man 5 apt.conf under APT::Immediate-Configure for details. (2)
WARNING:apt-get:E: Could not configure 'libc6:amd64'.
WARNING:apt-get:E: Could not perform immediate configuration on 'libgssapi-krb5-2:amd64'. Please see man 5 apt.conf under APT::Immediate-Configure for details. (2)
WARNING:apt-get:E: Could not configure 'libc6:amd64'.
WARNING:apt-get:E: Could not perform immediate configuration on 'libtirpc3:amd64'. Please see man 5 apt.conf under APT::Immediate-Configure for details. (2)
WARNING:apt-get:E: Could not configure 'libc6:amd64'.
WARNING:apt-get:E: Could not perform immediate configuration on 'libnsl2:amd64'. Please see man 5 apt.conf under APT::Immediate-Configure for details. (2)
WARNING:apt-get:E: Could not configure 'libc6:amd64'.
WARNING:apt-get:E: Could not perform immediate configuration on 'libnss-nis:amd64'. Please see man 5 apt.conf under APT::Immediate-Configure for details. (2)
Traceback (most recent call last):
  File "/home/grim/.local/bin/appimage-builder", line 18, in <module>
    __main__();
  File "/home/grim/.local/lib/python3.8/site-packages/AppImageBuilder/__main__.py", line 63, in __main__
    builder.build()
  File "/home/grim/.local/lib/python3.8/site-packages/AppImageBuilder/app_dir/builder.py", line 67, in build
    self._bundle_dependencies()
  File "/home/grim/.local/lib/python3.8/site-packages/AppImageBuilder/app_dir/builder.py", line 77, in _bundle_dependencies
    bundler.run()
  File "/home/grim/.local/lib/python3.8/site-packages/AppImageBuilder/app_dir/bundlers/apt/bundler.py", line 69, in run
    self._extend_partitions()
  File "/home/grim/.local/lib/python3.8/site-packages/AppImageBuilder/app_dir/bundlers/apt/bundler.py", line 136, in _extend_partitions
    raw_package_list = self.apt_get.generate_install_list(packages)
  File "/home/grim/.local/lib/python3.8/site-packages/AppImageBuilder/commands/apt_get.py", line 53, in generate_install_list
    raise AptGetError('Unable to download packages')
AppImageBuilder.commands.apt_get.AptGetError: Unable to download packages

```yaml
---
version: 1
AppDir:
  path: ./AppDir
  app_info:
    id: im.pidgin.Pidgin3
    name: Pidgin3
    icon: im.pidgin.Pidgin3
    version: !ENV ${VERSION}
    exec: usr/bin/pidgin3
  apt:
    arch: amd64
    sources:
      - sourceline: 'deb [arch=amd64] http://deb.debian.org/debian/ bullseye main'
        key_url: 'https://ftp-master.debian.org/keys/archive-key-10.asc'
    include:
      - dictionaries-common
      - gir1.2-gdkpixbuf-2.0
      - gir1.2-gtk-3.0
      - gir1.2-soup-2.4
      - gstreamer1.0-gl
      # - gstreamer1.0-plugins-bad # 100mb-ish only if we really **REALLY** need it
      - gstreamer1.0-plugins-good
      - gstreamer1.0-x
      - libavahi-client3
      - libavahi-glib1
      - libcanberra0
      - libcmark0.29.0
      - libfarstream-0.2-5
      - libfontconfig1
      - libfreetype6
      - libgadu3
      - libgirepository-1.0-1
      - libglib-object-introspection-perl
      - libglib-perl
      - libgmime-3.0-0
      - libgspell-1-2
      - libgstreamer-plugins-base1.0-0
      - libgstreamer1.0-0
      - libgtk-3-0
      - libgumbo1
      - libidn11
      - libidn2-0
      - libjson-glib-1.0-0
      # - libkf5wallet5 # 57mb
      - liblua5.3-0
      - libmeanwhile1
      - libperl5.30
      - libpython3.8
      - libsecret-1-0
      - libsoup2.4-1
      - libxss1
      - lua-lgi
      - python3-gi
    exclude:
      - adwaita-icon-theme
  files:
    exclude:
      - usr/share/man
      - usr/share/doc/*/README.*
      - usr/share/doc/*/changelog.*
      - usr/share/doc/*/NEWS.*
      - usr/share/doc/*/TODO.*
      - usr/include
  runtime:
    path_mappings:
      - /usr/lib/x86_64-linux-gnu/gplugin:$APPDIR/usr/lib/x86_64-linux-gnu/gplugin/
      - /usr/lib/x86_64-linux-gnu/purple-3:$APPDIR/usr/lib/x86_64-linux-gnu/purple-3/
      - /usr/lib/x86_64-linux-gnu/pidgin-3:$APPDIR/usr/lib/x86_64-linux-gnu/pidgin-3/
      - /usr/share/pidgin/:$APPDIR/usr/share/pidgin/
      - /usr/share/pixmaps/pidgin/:$APPDIR/usr/share/pixmaps/pidgin/
    env:
      XDG_DATA_DIRS: $APPDIR/share:$XDG_DATA_DIRS
AppImage:
  arch: x86_64
```
