### ISSUE TITLE
Pacman support

### ISSUE THREAD

**Issue by azubieta** [AppImageCrafters/appimage-builder#59]
Given the input below, appimage-builder must download the `bash` package along with its dependencies. The `filesystem` package and its dependencies must be excluded (dependencies should be excluded only if they are not required by other included package).

Once the packages are download they should be extracted using AppDir as root.

```
AppDir:
  pacman:
    include:
    - bash
    exclude:
    - filesystem
```

Questions:
- Is it possible?
- How?
