### ISSUE TITLE
Key 'QT_DEBUG_PLUGINS' error: 1 should be instance of 'str'

### ISSUE THREAD

**Issue by akontsevich** [AppImageCrafters/appimage-builder#73]
`appimage-builder`  stopped to for for us today, error is:

```
INFO:root:Downloading runtime: https://github.com/AppImage/AppImageKit/releases/download/continuous/runtime-x86_64
urllib.error.HTTPError: HTTP Error 404: Not Found
```
Temp issue or some fix available?

**Comment by akontsevich** [comment]
Also now getting errors for Qt/Kde application template:
```
  test:
    debian:
      image: appimagecrafters/tests-env:debian-stable
      command: "./AppRun"
      use_host_x: True
      env:
        - QT_DEBUG_PLUGINS=1
    centos:
      image: appimagecrafters/tests-env:centos-7
      command: "./AppRun"
      use_host_x: True
      env:
        - QT_DEBUG_PLUGINS=1
    arch:
      image: appimagecrafters/tests-env:archlinux-latest
      command: "./AppRun"
      use_host_x: True
      env:
        - QT_DEBUG_PLUGINS=1
    fedora:
      image: appimagecrafters/tests-env:fedora-30
      command: "./AppRun"
      use_host_x: True
      env:
        - QT_DEBUG_PLUGINS=1
```

Error is:
```
Key 'debian' error:
Key 'env' error:
'QT_DEBUG_PLUGINS=1' should be instance of 'dict'
```
@azubieta how to fix?
