### ISSUE TITLE
Taskcoach crashes when a window is opened.

### ISSUE THREAD

**Issue by fluks** [AppImageCrafters/appimage-builder#75]
I'm trying to make an appimage for Taskcoach.

```
version: 1
script:
  # Remove any previous build
  - rm -rf AppDir  | true
  # Make usr and icons dirs
  - mkdir -p AppDir/usr/src
  #- virtualenv --python python2 venv
  #- . venv/bin/activate
  # Install taskcoach from pip
  #- pip install --system --ignore-installed --prefix=/usr --root=AppDir taskcoach
  - python2 setup.py install --prefix=/usr --root=AppDir

AppDir:
  path: ./AppDir

  app_info:
    id: fi.julaiti.kapsi.fi.taskcoach
    name: taskcoach appimage
    icon: utilities-terminal
    version: 0.1.0
    # Set the python executable as entry point
    exec: usr/bin/python2
    # Set the application main script path as argument. Use '$@' to forward CLI parameters
    exec_args: "$APPDIR/usr/bin/taskcoach.py $@"

  apt:
    arch: amd64
    sources:
      - sourceline: 'deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ bionic main restricted universe multiverse'
        key_url: 'http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3b4fe6acc0b21f32'

    include:
      - python2.7
      - python-pkg-resources
      - x11-utils
      - python-chardet
      - python-dateutil
      - python-keyring
      - python-lockfile
      - python-pyparsing
      - python-squaremap
      - python-xdg
      - python-wxgtk3.0
      - python-wxversion
      - python-twisted-core
      - libxss1
      - fonts-dejavu
      - xdg-utils
      #- taskcoach
    exclude: []

  runtime:
    env:
      PATH: '${APPDIR}/usr/bin:${PATH}'
      # Set python home
      # See https://docs.python.org/3/using/cmdline.html#envvar-PYTHONHOME
      PYTHONHOME: '${APPDIR}/usr'
      # Path to the site-packages dir or other modules dirs
      # See https://docs.python.org/3/using/cmdline.html#envvar-PYTHONPATH
      PYTHONPATH: '${APPDIR}/usr/lib/python2.7/site-packages'

AppImage:
  update-information: 'gh-releases-zsync|AppImageCrafters|python-appimage-example|latest|python-appimage-*x86_64.AppImage.zsync'
  sign-key: None
  arch: x86_64
```
The program starts, but it crashes when I open a window. File > Open and it crashes.

```
/usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so
Gtk-Message: 21:59:32.123: Failed to load module "colorreload-gtk-module"

(taskcoach.py:506874): Gtk-WARNING **: 21:59:33.142: Could not load a pixbuf from /org/gtk/libgtk/theme/Adwaita/assets/check-symbolic.svg.
This may indicate that pixbuf loaders or the mime database could not be found.

(taskcoach.py:506874): Gtk-CRITICAL **: 21:59:33.260: gtk_widget_set_size_request: assertion 'height >= -1' failed
21.59.33: Debug: ClientToScreen cannot work when toplevel window is not shown
21.59.33: Debug: ScreenToClient cannot work when toplevel window is not shown

(taskcoach.py:506874): Gtk-CRITICAL **: 21:59:33.336: gtk_widget_set_size_request: assertion 'height >= -1' failed
21.59.33: Debug: ClientToScreen cannot work when toplevel window is not shown
21.59.33: Debug: ScreenToClient cannot work when toplevel window is not shown
21.59.33: Debug: ScreenToClient cannot work when toplevel window is not shown
21.59.33: Debug: ScreenToClient cannot work when toplevel window is not shown
21.59.33: Debug: ScreenToClient cannot work when toplevel window is not shown
21.59.33: Debug: ScreenToClient cannot work when toplevel window is not shown
21.59.33: Debug: ScreenToClient cannot work when toplevel window is not shown

(taskcoach.py:506874): Gdk-CRITICAL **: 21:59:33.935: gdk_visual_get_red_pixel_details: assertion 'GDK_IS_VISUAL (visual)' failed

(taskcoach.py:506874): Gdk-CRITICAL **: 21:59:33.935: gdk_visual_get_green_pixel_details: assertion 'GDK_IS_VISUAL (visual)' failed

(taskcoach.py:506874): Gdk-CRITICAL **: 21:59:33.935: gdk_visual_get_blue_pixel_details: assertion 'GDK_IS_VISUAL (visual)' failed

(taskcoach.py:506874): Gdk-CRITICAL **: 21:59:33.935: gdk_visual_get_depth: assertion 'GDK_IS_VISUAL (visual)' failed
/usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgioremote-volume-monitor.so
/usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so
/usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgioremote-volume-monitor.so
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
```
