### ISSUE TITLE
Looking for libQt5Core library in /lib64 when running appimage in ScientificLinux7, while runs fine in Fedora22 and CentOS8.3.2011

### ISSUE THREAD

**Issue by lopippo** [AppImageCrafters/appimage-builder#82]
Greetings, 

I successfully created an AppImage for my software on Debian Testing that I could run succesfully on Fedora22 and CentOS8.3.2011, which already is a feat :-)

When I tried that very same AppImage on ScientificLinux7 (based on CentOS), the image complains that /lib64/libQ5Core.so5: version Qt_5.15 was not found (required by /tmp/.mount_mineXpc3J4Y2/usr/bin/minexpert2).

I thought this was related to the fact that rpm-based distribs have the 64 bits libs in /lib64 and not in /usr/lib/x86_64-linux-gnu, so I thought I'd make manually copy /usr/lib/x86_64-linux-gnu to /lib64 in the AppDir directory. Odd, at least, because Fedora is rpm-based and also has the libs in lib64, I guess. Anyway, doing that did not help. 

I tried a bunch of other manipulations, but to no avail.

Thank you for your kind attention,

Sincerely,
Filippo

My yml:
```
# appimage-builder recipe see https://appimage-builder.readthedocs.io for details
version: 1
AppDir:
  path: ./AppDir
  app_info:
    id: minexpert2
    name: mineXpert2
    icon: minexpert2
    version: 7.4.0
    exec: usr/bin/minexpert2
    exec_args: $@
  runtime:
    env:
      APPDIR_LIBRARY_PATH: $APPDIR/lib/x86_64-linux-gnu:$APPDIR/usr/lib/x86_64-linux-gnu:$APPDIR/lib64
    path_mappings:
      - /usr/share/doc/minexpert2/:$APPDIR/usr/share/doc/minexpert2/
      - $APPDIR/usr/lib/x86_64-linux-gnu/:$APPDIR/lib64/
  apt:
    arch: amd64
    allow_unauthenticated: true
    sources:
    - sourceline: deb http://deb.debian.org/debian/ testing main non-free contrib
    - sourceline: deb http://security.debian.org/debian-security buster/updates main
        contrib non-free
    - sourceline: deb http://deb.debian.org/debian/ testing-updates main contrib non-free
    - sourceline: deb http://deb.debian.org/debian/ testing-backports main contrib
        non-free
    - sourceline: deb [trusted=yes] http://reprepro.localhost/ unstable main
    include:
    - minexpert2
    - minexpert2-doc
    - graphicsmagick-imagemagick-compat
    - libgomp1
    - libfreetype6
    - libqt5svg5
    - libqt5xml5
    - libqt5printsupport5
    - libqcustomplot2.0
    - libisospec++2
    - libpappsomspp0
    - libpappsomspp-widget0
    exclude: []
  files:
    exclude:
    - usr/share/man
    - usr/share/doc/*/README.*
    - usr/share/doc/*/changelog.*
    - usr/share/doc/*/NEWS.*
    - usr/share/doc/*/TODO.*
[ snip test section ] 
AppImage:
  arch: x86_64
  update-information: None
  #sign-key: B053304E17D6D419DD9B465141AB484D7694CF42
  ```
